### ISSUE TITLE
dotnet stopped working

### ISSUE THREAD

**Issue by sidmarvel** [Kwoth/NadekoBot#1121]
1st time user
Nadeko latest version
Process stops and error window appears.
dotnet has stopped working
![capture](https://cloud.githubusercontent.com/assets/26347299/23824548/a6d01f04-069e-11e7-8907-933f097b2c7e.JPG)

Using Win 8.1
Below is the CMD log

1.Download Latest Build
2.Download Stable Build
3.Run NadekoBot (normally)
4.Run NadekoBot with Auto Restart (check "if" nadeko is working properly, before
 using this)
5.Setup credentials.json
6.Install ffmpeg (for music)
7.To exit

Make sure you are running NadekoInstaller.bat as Administrator!

Enter your choice: [1,2,3,4,5,6,7]?3

Running Nadeko Normally, "if" you are running this to check Nadeko, use ".die" c
ommand on discord to stop Nadeko.

Waiting for  7 seconds, press a key to continue ...
Project Discord.Net.Core (.NETStandard,Version=v1.3) was previously compiled. Sk
ipping compilation.
Project Discord.Net.Commands (.NETStandard,Version=v1.3) was previously compiled
. Skipping compilation.
Project Discord.Net.Rest (.NETStandard,Version=v1.3) was previously compiled. Sk
ipping compilation.
Project Discord.Net.WebSocket (.NETStandard,Version=v1.3) was previously compile
d. Skipping compilation.
Project NadekoBot (.NETCoreApp,Version=v1.0) was previously compiled. Skipping c
ompilation.
21:02:52 NadekoBot | Starting NadekoBot v1.23
21:02:53 ImagesService | Loading images...
21:02:53 ImagesService | Images loaded after 0.02s!

Unhandled Exception: Discord.Net.HttpException: The server responded with error
0: 401: Unauthorized
   at Discord.Net.Queue.RequestBucket.<SendAsync>d__18.MoveNext() in K:\Nadeko\N
adekoBot\Discord.Net\src\Discord.Net.Rest\Net\Queue\RequestQueueBucket.cs:line 1
17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.Net.Queue.RequestQueue.<SendAsync>d__14.MoveNext() in K:\Nadeko\Na
dekoBot\Discord.Net\src\Discord.Net.Rest\Net\Queue\RequestQueue.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.API.DiscordRestApiClient.<SendInternalAsync>d__62.MoveNext() in K:
\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.Rest\DiscordRestApiClient.cs:line
263
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.API.DiscordRestApiClient.<SendAsync>d__57`1.MoveNext() in K:\Nadek
o\NadekoBot\Discord.Net\src\Discord.Net.Rest\DiscordRestApiClient.cs:line 223
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.API.DiscordRestApiClient.<GetVoiceRegionsAsync>d__134.MoveNext() i
n K:\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.Rest\DiscordRestApiClient.cs:l
ine 1087
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.WebSocket.DiscordSocketClient.<OnLoginAsync>d__93.MoveNext() in K:
\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.WebSocket\DiscordSocketClient.cs:l
ine 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__33.MoveNext() in K:\
Nadeko\NadekoBot\Discord.Net\src\Discord.Net.Rest\BaseDiscordClient.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__33.MoveNext() in K:\
Nadeko\NadekoBot\Discord.Net\src\Discord.Net.Rest\BaseDiscordClient.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginAsync>d__32.MoveNext() in K:\Nadeko\N
adekoBot\Discord.Net\src\Discord.Net.Rest\BaseDiscordClient.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.WebSocket.DiscordShardedClient.<OnLoginAsync>d__32.MoveNext() in K
:\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.WebSocket\DiscordShardedClient.cs
:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__33.MoveNext() in K:\
Nadeko\NadekoBot\Discord.Net\src\Discord.Net.Rest\BaseDiscordClient.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__33.MoveNext() in K:\
Nadeko\NadekoBot\Discord.Net\src\Discord.Net.Rest\BaseDiscordClient.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginAsync>d__32.MoveNext() in K:\Nadeko\N
adekoBot\Discord.Net\src\Discord.Net.Rest\BaseDiscordClient.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NadekoBot.NadekoBot.<RunAsync>d__56.MoveNext() in K:\Nadeko\NadekoBot\src\
NadekoBot\NadekoBot.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__58.MoveNext() in K:\Nadeko\Nadeko
Bot\src\NadekoBot\NadekoBot.cs:line 154
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NadekoBot.Program.Main(String[] args) in K:\Nadeko\NadekoBot\src\NadekoBot
\Program.cs:line 6

**Comment by ManuelFte** [comment]
Your bot token is wrong, probably you put the Client ID or Client Secret instead. Read the guide carefully.

https://cdn.discordapp.com/attachments/117523346618318850/280809863154499585/Capture.png
