### ISSUE TITLE
I am getting such an error when launching a nadeko bot on a new server.

### ISSUE THREAD

**Issue by DaYWhiTe** [Kwoth/NadekoBot#1202]
root@s2:~# ./linuxAIO.sh

Welcome to NadekoBot.
1. Download Dev Build (Latest)
2. Download Stable Build
3. Run Nadeko (Normally)
4. Run Nadeko with Auto Restart (Run Nadeko normally before using this.)
5. Auto-Install Prerequisites (For Ubuntu, Debian and CentOS)
6. Set up credentials.json (If you have downloaded NadekoBot already.)
7. To Exit
Choose [1 or 2] to Download, [3 or 4] to Run, or [7] to Exit3

Running Nadeko Normally, if you are running this to check Nadeko, use .die command on discord to stop Nadeko.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147  100   147    0     0    348      0 --:--:-- --:--:-- --:--:--   349
100   308  100   308    0     0    672      0 --:--:-- --:--:-- --:--:--   672
NadekoBot 1.0
Mirai was here.
Dotnet installed.
Running NadekoBot. Please wait.
Project Discord.Net.Core (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Discord.Net.Commands (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Discord.Net.Rest (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Discord.Net.WebSocket (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project NadekoBot (.NETCoreApp,Version=v1.0) will be compiled because inputs were modified
Compiling NadekoBot for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:14.2274573

16:52:59 NadekoBot | Starting NadekoBot v1.3a
16:53:00 ImagesService | Loading images...
16:53:00 ImagesService | Images loaded after 0.03s!

Unhandled Exception: Discord.Net.HttpException: The server responded with error 0: 401: Unauthorized
   at Discord.Net.Queue.RequestBucket.<SendAsync>d__18.MoveNext() in /root/NadekoBot/Discord.Net/src/Discord.Net.Rest/Net/Queue/RequestQueueBucket.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Queue.RequestQueue.<SendAsync>d__14.MoveNext() in /root/NadekoBot/Discord.Net/src/Discord.Net.Rest/Net/Queue/RequestQueue.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendInternalAsync>d__62.MoveNext() in /root/NadekoBot/Discord.Net/src/Discord.Net.Rest/DiscordRestApiClient.cs:line 263
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendAsync>d__57`1.MoveNext() in /root/NadekoBot/Discord.Net/src/Discord.Net.Rest/DiscordRestApiClient.cs:line 223
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<GetVoiceRegionsAsync>d__134.MoveNext() in /root/NadekoBot/Discord.Net/src/Discord.Net.Rest/DiscordRestApiClient.cs:line 1087
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.DiscordSocketClient.<OnLoginAsync>d__93.MoveNext() in /root/NadekoBot/Discord.Net/src/Discord.Net.WebSocket/DiscordSocketClient.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__33.MoveNext() in /root/NadekoBot/Discord.Net/src/Discord.Net.Rest/BaseDiscordClient.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__33.MoveNext() in /root/NadekoBot/Discord.Net/src/Discord.Net.Rest/BaseDiscordClient.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginAsync>d__32.MoveNext() in /root/NadekoBot/Discord.Net/src/Discord.Net.Rest/BaseDiscordClient.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.DiscordShardedClient.<OnLoginAsync>d__32.MoveNext() in /root/NadekoBot/Discord.Net/src/Discord.Net.WebSocket/DiscordShardedClient.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__33.MoveNext() in /root/NadekoBot/Discord.Net/src/Discord.Net.Rest/BaseDiscordClient.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__33.MoveNext() in /root/NadekoBot/Discord.Net/src/Discord.Net.Rest/BaseDiscordClient.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginAsync>d__32.MoveNext() in /root/NadekoBot/Discord.Net/src/Discord.Net.Rest/BaseDiscordClient.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAsync>d__56.MoveNext() in /root/NadekoBot/src/NadekoBot/NadekoBot.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__58.MoveNext() in /root/NadekoBot/src/NadekoBot/NadekoBot.cs:line 156
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Program.Main(String[] args) in /root/NadekoBot/src/NadekoBot/Program.cs:line 6

**Comment by samdivaio** [comment]
Your bot token is incorrect, read the guide again.

**Comment by DaYWhiTe** [comment]
Thank you
