### ISSUE TITLE
Error when starting up.

### ISSUE THREAD

**Issue by MovingBlast** [Kwoth/NadekoBot#1219]
I think I may not have installed something correctly but anyways, here's the error.

Project Discord.Net.Core (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Discord.Net.Commands (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Discord.Net.Rest (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Discord.Net.WebSocket (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project NadekoBot (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
19:02:52 BotCredentials | Could not parse the JSON file. Error on line number '6': '"OwnerIds": [310699494700482560
105635576866156544'.
19:02:52 BotCredentials | System.FormatException: Could not parse the JSON file. Error on line number '6': '"OwnerIds": [310699494700482560
105635576866156544'. ---> Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: 1. Path 'OwnerIds[0]', line 6, position 4.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at NadekoBot.Services.Impl.BotCredentials..ctor() in C:\Users\Besrat\Desktop\Nadeko\NadekoBot\src\NadekoBot\Services\Impl\BotCredentials.cs:line 56

Unhandled Exception: System.TypeInitializationException: The type initializer for 'NadekoBot.NadekoBot' threw an exception. ---> System.FormatException: Could not parse the JSON file. Error on line number '6': '"OwnerIds": [310699494700482560
105635576866156544'. ---> Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: 1. Path 'OwnerIds[0]', line 6, position 4.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at NadekoBot.Services.Impl.BotCredentials..ctor() in C:\Users\Besrat\Desktop\Nadeko\NadekoBot\src\NadekoBot\Services\Impl\BotCredentials.cs:line 94
   at NadekoBot.NadekoBot..cctor() in C:\Users\Besrat\Desktop\Nadeko\NadekoBot\src\NadekoBot\NadekoBot.cs:line 54
   --- End of inner exception stack trace ---
   at NadekoBot.Program.Main(String[] args) in C:\Users\Besrat\Desktop\Nadeko\NadekoBot\src\NadekoBot\Program.cs:line 6
NadekoBot has been succesfully stopped, press any key to close this window.

Any response would be good.

**Comment by shikhir-arora** [comment]
```
{
  "ClientId": 123123123,
  "BotId": null,
  "Token": "",
  "OwnerIds": [
    [ "ID1", "ID2" ],
  ],
  "LoLApiKey": "",
  "GoogleApiKey": "",
  "MashapeKey": "",
  "OsuApiKey": "",
  "SoundCloudClientId": "",
  "CarbonKey": "",
  "Db": null,
  "TotalShards": 1
}
```

You'd want to make sure you're formatting the OwnerIDs in that fashion in your config.

**Comment by MovingBlast** [comment]
Ok so I figured out how to do the OwnerID properly but the issue is I get the same thing.

Oh and here's the OwnerID stuff just to make sure I did it right.

{
  "ClientId": 312275864211554305
  "BotId": 312275864211554305,
  "Token": "*CENSORED*",
  "OwnerIds": [310699494700482560]

  "LoLApiKey": "",
  "GoogleApiKey": "",
  "MashapeKey": "",
  "OsuApiKey": "",
  "SoundCloudClientId": "",
  "Db": null,
  "TotalShards": 1
}

Be free to tell me if I messed up again.

**Comment by Deivedux** [comment]
```"OwnerIds": [
    [ 310699494700482560,  105635576866156544 ]
  ],```

Use this.

**Comment by MovingBlast** [comment]
20:11:34 BotCredentials | Could not parse the JSON file. Error on line number '3': '"ClientId": 312275864211554305
"BotId": 312275864211554305,'.
20:11:35 BotCredentials | System.FormatException: Could not parse the JSON file. Error on line number '3': '"ClientId": 312275864211554305
"BotId": 312275864211554305,'. ---> Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: ". Path 'ClientId', line 3, position 2.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at NadekoBot.Services.Impl.BotCredentials..ctor() in C:\Users\Besrat\Desktop\Nadeko\NadekoBot\src\NadekoBot\Services\Impl\BotCredentials.cs:line 56

Unhandled Exception: System.TypeInitializationException: The type initializer for 'NadekoBot.NadekoBot' threw an exception. ---> System.FormatException: Could not parse the JSON file. Error on line number '3': '"ClientId": 312275864211554305
"BotId": 312275864211554305,'. ---> Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: ". Path 'ClientId', line 3, position 2.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at NadekoBot.Services.Impl.BotCredentials..ctor() in C:\Users\Besrat\Desktop\Nadeko\NadekoBot\src\NadekoBot\Services\Impl\BotCredentials.cs:line 94
   at NadekoBot.NadekoBot..cctor() in C:\Users\Besrat\Desktop\Nadeko\NadekoBot\src\NadekoBot\NadekoBot.cs:line 54
   --- End of inner exception stack trace ---
   at NadekoBot.Program.Main(String[] args) in C:\Users\Besrat\Desktop\Nadeko\NadekoBot\src\NadekoBot\Program.cs:line 6

I'm beginning to think it's either:

A. Possibly something else.

Or B. I an LITERALLY unable to listen to instrucitons.

**Comment by shikhir-arora** [comment]
```

{
  "ClientId": 252872082315018240,
  "BotId": 252872082315018240,
  "Token": "",
  "OwnerIds": [
   123456, 123456
  ],
  "LoLApiKey": "",
  "GoogleApiKey": "",
  "MashapeKey": "",
  "OsuApiKey": "",
  "SoundCloudClientId": "",
  "Db": null,
  "TotalShards": 1
}
```
You forgot a comma after ClientID. It won't matter if you put them in quotes or not.

**Comment by MovingBlast** [comment]
Waiting for  0 seconds, press a key to continue ...
Project Discord.Net.Core (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Discord.Net.Commands (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Discord.Net.Rest (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Discord.Net.WebSocket (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project NadekoBot (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
20:33:05 BotCredentials | Could not parse the JSON file. Error on line number '6': '"OwnerIds": [ 310699494700482560,  105635576866156544 ]
],```'.
20:33:05 BotCredentials | System.FormatException: Could not parse the JSON file. Error on line number '6': '"OwnerIds": [ 310699494700482560,  105635576866156544 ]
],```'. ---> Newtonsoft.Json.JsonReaderException: JsonToken EndArray is not valid for closing JsonType Object. Path '', line 6, position 3.
   at Newtonsoft.Json.JsonReader.ValidateEnd(JsonToken endToken)
   at Newtonsoft.Json.JsonTextReader.ParsePostValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at NadekoBot.Services.Impl.BotCredentials..ctor() in C:\Users\Besrat\Desktop\Nadeko\NadekoBot\src\NadekoBot\Services\Impl\BotCredentials.cs:line 56

Unhandled Exception: System.TypeInitializationException: The type initializer for 'NadekoBot.NadekoBot' threw an exception. ---> System.FormatException: Could not parse the JSON file. Error on line number '6': '"OwnerIds": [ 310699494700482560,  105635576866156544 ]
],```'. ---> Newtonsoft.Json.JsonReaderException: JsonToken EndArray is not valid for closing JsonType Object. Path '', line 6, position 3.
   at Newtonsoft.Json.JsonReader.ValidateEnd(JsonToken endToken)
   at Newtonsoft.Json.JsonTextReader.ParsePostValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at NadekoBot.Services.Impl.BotCredentials..ctor() in C:\Users\Besrat\Desktop\Nadeko\NadekoBot\src\NadekoBot\Services\Impl\BotCredentials.cs:line 94
   at NadekoBot.NadekoBot..cctor() in C:\Users\Besrat\Desktop\Nadeko\NadekoBot\src\NadekoBot\NadekoBot.cs:line 54
   --- End of inner exception stack trace ---
   at NadekoBot.Program.Main(String[] args) in C:\Users\Besrat\Desktop\Nadeko\NadekoBot\src\NadekoBot\Program.cs:line 6
NadekoBot has been succesfully stopped, press any key to close this window.

Now it's the bloody OwnerID. I'm so close to bashing my head against my table now.

**Comment by shikhir-arora** [comment]
You just left a [ on the left side missing. For just two ID's, do it like @Deivedux said.

```
{
  "ClientId": 252872082315018240,
  "BotId": 252872082315018240,
  "Token": "",
  "OwnerIds": [
   252872082315018240, 
   252872082315018240
  ],
  "LoLApiKey": "",
  "GoogleApiKey": "",
  "MashapeKey": "",
  "OsuApiKey": "",
  "SoundCloudClientId": "",
  "Db": null,
  "TotalShards": 1
}
```

**Comment by MovingBlast** [comment]
It finally began working! Thanks to the both of you! :3
