### ISSUE TITLE
.ban no longer working

### ISSUE THREAD

**Issue by bartdebever** [Kwoth/NadekoBot#1231]
Heyo. I have a Nadeko bot on autoupdate stable build and we have an issue with the latest version this morning. The .ban command is not working currently giving me this error:

```17:25:44 CommandHandler | Error in CommandHandler
17:25:44 CommandHandler | System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.WebSocket.SocketGuildChannel.GetPermissionOverwrite(IRole role) in C:\Users\bartd\Desktop\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.WebSocket\Entities\Channels\SocketGuildChannel.cs:line 71
   at Discord.Permissions.ResolveChannel(IGuild guild, IGuildUser user, IGuildChannel channel, UInt64 guildPermissions) in C:\Users\bartd\Desktop\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.Core\Utils\Permissions.cs:line 128
   at Discord.WebSocket.SocketTextChannel.<get_Users>b__10_0(SocketGuildUser x) in C:\Users\bartd\Desktop\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.WebSocket\Entities\Channels\SocketTextChannel.cs:line 23
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Discord.WebSocket.SocketTextChannel.get_Users() in C:\Users\bartd\Desktop\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.WebSocket\Entities\Channels\SocketTextChannel.cs:line 23
   at Discord.WebSocket.SocketGuildChannel.Discord.IChannel.GetUsersAsync(CacheMode mode, RequestOptions options) in C:\Users\bartd\Desktop\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.WebSocket\Entities\Channels\SocketGuildChannel.cs:line 156
   at Discord.Commands.UserTypeReader`1.<Read>d__0.MoveNext() in C:\Users\bartd\Desktop\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.Commands\Readers\UserTypeReader.cs:line 15
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.ParameterInfo.<Parse>d__30.MoveNext() in C:\Users\bartd\Desktop\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.Commands\Info\ParameterInfo.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandParser.<ParseArgs>d__1.MoveNext() in C:\Users\bartd\Desktop\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.Commands\CommandParser.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ParseAsync>d__35.MoveNext() in C:\Users\bartd\Desktop\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.Commands\Info\CommandInfo.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Services.CommandHandler.<ExecuteCommand>d__30.MoveNext() in C:\Users\bartd\Desktop\Nadeko\NadekoBot\src\NadekoBot\Services\CommandHandler.cs:line 442
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Services.CommandHandler.<TryRunCommand>d__28.MoveNext() in C:\Users\bartd\Desktop\Nadeko\NadekoBot\src\NadekoBot\Services\CommandHandler.cs:line 385
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Services.CommandHandler.<>c__DisplayClass27_0.<<MessageReceivedHandler>b__0>d.MoveNext() in C:\Users\bartd\Desktop\Nadeko\NadekoBot\src\NadekoBot\Services\CommandHandler.cs:line 268
17:25:47 CommandHandler | Error in CommandHandler
17:25:47 CommandHandler | System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.WebSocket.SocketGuildChannel.GetPermissionOverwrite(IRole role) in C:\Users\bartd\Desktop\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.WebSocket\Entities\Channels\SocketGuildChannel.cs:line 71
   at Discord.Permissions.ResolveChannel(IGuild guild, IGuildUser user, IGuildChannel channel, UInt64 guildPermissions) in C:\Users\bartd\Desktop\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.Core\Utils\Permissions.cs:line 128
   at Discord.WebSocket.SocketTextChannel.<get_Users>b__10_0(SocketGuildUser x) in C:\Users\bartd\Desktop\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.WebSocket\Entities\Channels\SocketTextChannel.cs:line 23
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Discord.WebSocket.SocketTextChannel.get_Users() in C:\Users\bartd\Desktop\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.WebSocket\Entities\Channels\SocketTextChannel.cs:line 23
   at Discord.WebSocket.SocketGuildChannel.Discord.IChannel.GetUsersAsync(CacheMode mode, RequestOptions options) in C:\Users\bartd\Desktop\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.WebSocket\Entities\Channels\SocketGuildChannel.cs:line 156
   at Discord.Commands.UserTypeReader`1.<Read>d__0.MoveNext() in C:\Users\bartd\Desktop\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.Commands\Readers\UserTypeReader.cs:line 15
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.ParameterInfo.<Parse>d__30.MoveNext() in C:\Users\bartd\Desktop\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.Commands\Info\ParameterInfo.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandParser.<ParseArgs>d__1.MoveNext() in C:\Users\bartd\Desktop\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.Commands\CommandParser.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ParseAsync>d__35.MoveNext() in C:\Users\bartd\Desktop\Nadeko\NadekoBot\Discord.Net\src\Discord.Net.Commands\Info\CommandInfo.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Services.CommandHandler.<ExecuteCommand>d__30.MoveNext() in C:\Users\bartd\Desktop\Nadeko\NadekoBot\src\NadekoBot\Services\CommandHandler.cs:line 442
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Services.CommandHandler.<TryRunCommand>d__28.MoveNext() in C:\Users\bartd\Desktop\Nadeko\NadekoBot\src\NadekoBot\Services\CommandHandler.cs:line 385
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Services.CommandHandler.<>c__DisplayClass27_0.<<MessageReceivedHandler>b__0>d.MoveNext() in C:\Users\bartd\Desktop\Nadeko\NadekoBot\src\NadekoBot\Services\CommandHandler.cs:line 268```

**Comment by Kwoth** [comment]
That's a bug that occasionally happens, seems to be related to the old discord.net version we're using, you can reopen this issue if it still continues happening when 1.4 is released, which uses newest discord.net.

**Comment by bartdebever** [comment]
Running version 1.6.4 same issue still occurring

`15:34:37 NadekoBot | Starting NadekoBot v1.6.4
15:34:37 NadekoBot | Shard 0 logging in ...
15:34:38 NadekoBot | Shard 0 logged in.
15:34:38 NadekoBot | Shard 0 loading services...
15:34:39 NadekoStrings | Loaded 23 languages in 0.07s
15:34:39 ServiceProvider | All services loaded in 0.50s
15:34:39 NadekoBot | Shard 0 connected in 2.82s
15:34:40 NadekoBot | Shard 0 ready.
15:34:45 SelfService | Created 3 out of 3 owner message channels.
15:35:13 CommandHandler | Error in CommandHandler
15:35:13 CommandHandler | System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.WebSocket.SocketGuildChannel.GetPermissionOverwrite(IRole role)
   at Discord.Permissions.ResolveChannel(IGuild guild, IGuildUser user, IGuildChannel channel, UInt64 guildPermissions)
   at Discord.WebSocket.SocketTextChannel.<get_Users>b__10_0(SocketGuildUser x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Discord.WebSocket.SocketTextChannel.get_Users()
   at Discord.WebSocket.SocketGuildChannel.Discord.IChannel.GetUsersAsync(CacheMode mode, RequestOptions options)
   at Discord.Commands.UserTypeReader`1.<Read>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.ParameterInfo.<Parse>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandParser.<ParseArgs>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ParseAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Services.CommandHandler.<ExecuteCommand>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Services.CommandHandler.<TryRunCommand>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Services.CommandHandler.<MessageReceivedHandler>d__43.MoveNext()`
