### ISSUE TITLE
Music is silent on CentOS 7 x86_64

### ISSUE THREAD

**Issue by polyzium** [Kwoth/NadekoBot#1308]
As the title says.After i execute the command, bot joins the channel and music doesn't play. I followed the Linux guide and installed the dependencies, i installed ffmpeg-libs, devel versions and compat versions of ffmpeg. API keys are properly configured. But the music is still silent.

Any fix on that?

**Comment by xnaas** [comment]
Sounds like the same thing that happens if dotnet is missing on a Windows installation of the bot.

I've never setup the bot on Linux, but there must be some small requirement you missed? I assume you were just following [this guide](http://nadekobot.readthedocs.io/en/latest/guides/Linux%20Guide/)?

**Comment by polyzium** [comment]
Yes i followed that guide. I installed all prerequistes (did i write that right?) and installed additional ffmpeg packages

**Comment by samdivaio** [comment]
Possibly related to .NET Core SDK, I am sure Kwoth can patch that. 
Tested it and 
```16:47:27 Song | Buffering successfull
16:47:27 Song | Prebuffering successfully completed in 00:00:01.4205819

Enter command: <target>|all <time>|-1 <command>[ <argument>]
Buffering done.
```

**Comment by Kwoth** [comment]
@samdivaio did you fix this in that linux pr?

**Comment by samdivaio** [comment]
No, its related to .NET Core. 
I tried `-nostdin` to remove the error `Enter command: <target>|all <time>|-1 <command>[ <argument>]`. 

But can't make the bot play, the thing is similar to Windows issue, where bot can't play music if there is no .NET Core SDK installed even though NadekoBot is packed with it. 
That is what exactly happening with CentOS.

Also I have tested with 1.4 and 1.3 on a same `CentOS 7.3.1611 x64` server. The music played with 1.3 but not with 1.4.

**Comment by Kwoth** [comment]
dotnet has nothing to do with music. I thought this is ffmpeg command failing because you had that ffmpeg install typo?

**Comment by samdivaio** [comment]
Not really, he installed them manually. If its not dotnet then it could be related to how ffmpeg is now executed? Is it different from v1.3?

**Comment by Kwoth** [comment]
Nope, it's the same

**Comment by MrAdder** [comment]
Its FFMPEG Related

08:49:13 Song | Buffering successfull
08:49:13 Song | Prebuffering successfully completed in 00:00:02.8913538

Enter command: <target>|all <time>|-1 <command>[ <argument>]
Parse error, at least 3 arguments were expected, only 1 given in string 'ho "Done"'

**Comment by polyzium** [comment]
Really weird, maybe ffmpeg got updated?

**Comment by MrAdder** [comment]
Yeah I believe it did as I just tested on my other server thats running the same version of centos and that works just havent updated it

**Comment by polyzium** [comment]
We need to wait for @Kwoth or others to fix it then

**Comment by samdivaio** [comment]
```Enter command: |all |-1 [ ]
Parse error, at least 3 arguments were expected, only 1 given in string 'ho "Done"'``` 
Happens when ffmpeg reads from stdin, `-nostdin` can fix it, apart from that.

```my other server thats running the same version of centos and that works just havent updated it```
Do you mean you are running same CentOS 7.3.1611 x64 and have Nadeko 1.3x installed and it works for you?

**Comment by polyzium** [comment]
@samdivaio You mean i must compile ffmpeg not to use stdin?

**Comment by samdivaio** [comment]
@polyzium you cant fix it the `-nostdin` is to remove the parse error. The issue is with latest .net core sdk for centOS, ffmpeg cant pipe the steam for some reason.

For music functions on your server either upgrade to ubuntu 14+ or downgrade your bot to 1.3x.
1.3x uses old .NET Core SDK so you need to follow the [1.3x guide here](https://nadekobot.readthedocs.io/en/1.3x/guides/Linux%20Guide/)

**Comment by polyzium** [comment]
Will openSUSE work or is this issue present on all RPM-based distros?

**Comment by samdivaio** [comment]
I am not sure. I can't test it atm.

**Comment by TheDeadCode** [comment]
Yeah, can confirm.

Suprised no one uses the bot on the *true and only server system*.

```[root@cdn ~]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)```

7.3.1611 also

**Comment by Kwoth** [comment]
Did you try updating, upgrading ffmpeg to 3.3+ and trying again?

**Comment by Kwoth** [comment]
So, Is this still happening, or can I close it? Music should be pretty stable now.

**Comment by TheDeadCode** [comment]
I had a few things to do; Let me add ffmpeg 3.3 and test

**Comment by Kwoth** [comment]
@TheDeadCode any updates?

**Comment by TheDeadCode** [comment]
```
08:56:50 YoutubeResolveStrategy | System.ComponentModel.Win32Exception: No such file or directory
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NadekoBot.Services.Impl.YtdlOperation.<GetDataAsync>d__2.MoveNext() in /root/discord/nadeko/NadekoBot/src/NadekoBot/Services/Impl/Ytdl.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Services.Music.SongResolver.Strategies.YoutubeResolveStrategy.<ResolveSong>d__2.MoveNext() in /root/discord/nadeko/NadekoBot/src/NadekoBot/Services/Music/SongResolver/Strategies/YoutubeResolveStrategy.cs:line 27
```

**Comment by TheDeadCode** [comment]
Seems you rely on `youtube-dl`, which has need been build on Linux

**Comment by TheDeadCode** [comment]
Added youtube-dl

```
09:05:02 NadekoModule | Getting player
09:05:02 MusicService | Checks
09:05:02 MusicService | Get or add
09:05:02 MusicService | Getting default volume
09:05:02 MusicService | Creating musicplayer instance
09:05:02 MusicPlayer | Initialized
09:05:02 MusicPlayer | Loop started
09:05:02 MusicService | Subscribing
09:05:02 MusicService | Done creating
09:05:02 NadekoModule | Resolving song
09:05:03 YoutubeResolveStrategy | Getting link
09:05:04 SelfService | Created 2 out of 2 owner message channels.
09:05:05 NadekoModule | Queueing song
09:05:05 NadekoModule | Added
09:05:05 MusicPlayer | Starting
09:05:05 NadekoModule | --------------
09:05:05 CommandHandler | Command Executed after 0.015/0.033/3.053s
        User: Felix | DeadCode#3679 [105845005926559744]
        Server: MuchoHentai.com [329113314678276096]
        Channel: admin-only [330907896982274068]
        Message: .q hello adele
09:05:08 MusicPlayer | Get current user
09:05:08 MusicPlayer | Connecting
09:05:08 SongBuffer | >>> https://r17---sn-1gi7zn7l.googlevideo.com/videoplayback?lmt=1445520219092080&dur=366.821&key=yt6&ip=91.215.158.36&itag=251&id=o-ANu0fc1stoUzhYxlbTaxxWVZm3NZY4c13i15zT9P8qo7&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mime=audio%2Fwebm&source=youtube&pl=23&gir=yes&ipbits=0&mm=31&mn=sn-1gi7zn7l&keepalive=yes&clen=6020814&requiressl=yes&expire=1499771028&mt=1499749137&mv=u&ei=NFxkWbDBEcTScMXEgfgF&ms=au&signature=451572A579E4101D2DE3D45FFD7123022B1B9373.FADFDC2BB3B7E4918279EF518326F709CF38E1&ratebypass=yes: Protocol not found
09:05:08 SongBuffer | >>> Did you mean file:https://r17---sn-1gi7zn7l.googlevideo.com/videoplayback?lmt=1445520219092080&dur=366.821&key=yt6&ip=91.215.158.36&itag=251&id=o-ANu0fc1stoUzhYxlbTaxxWVZm3NZY4c13i15zT9P8qo7&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mime=audio%2Fwebm&source=youtube&pl=23&gir=yes&ipbits=0&mm=31&mn=sn-1gi7zn7l&keepalive=yes&clen=6020814&requiressl=yes&expire=1499771028&mt=1499749137&mv=u&ei=NFxkWbDBEcTScMXEgfgF&ms=au&signature=451572A579E4101D2DE3D45FFD7123022B1B9373.FADFDC2BB3B7E4918279EF518326F709CF38E1&ratebypass=yes?
09:05:09 MusicPlayer | Connected, stopping
09:05:09 MusicPlayer | Disconnected
09:05:10 MusicPlayer | Connecting
09:05:11 MusicPlayer | Got Audio client
09:05:11 MusicPlayer | Created pcm stream
09:05:11 MusicPlayer | Song removed because it can't play
09:05:11 MusicPlayer | Next song
```

**Comment by TheDeadCode** [comment]
After reading the code, the issue was linked to ffmpeg missing TLS input stream.

```bash
yum install openssl-devel -y
./configure --with-openssl
make
make install
```

I built ffmpeg w/ tls suppor.

Now, there is no error, but still no sound:

```
09:55:30 NadekoModule | Getting player
09:55:30 MusicService | Checks
09:55:30 MusicService | Get or add
09:55:30 MusicService | Getting default volume
09:55:30 MusicService | Creating musicplayer instance
09:55:30 MusicPlayer | Initialized
09:55:30 MusicPlayer | Loop started
09:55:30 MusicService | Subscribing
09:55:30 MusicService | Done creating
09:55:30 NadekoModule | Resolving song
09:55:30 YoutubeResolveStrategy | Getting link
09:55:33 SelfService | Created 2 out of 2 owner message channels.
09:55:37 NadekoModule | Queueing song
09:55:37 NadekoModule | Added
09:55:37 NadekoModule | --------------
09:55:37 CommandHandler | Command Executed after 0.015/0.033/7.183001s
        User: Felix | DeadCode#3679 [105845005926559744]
        Server: MuchoHentai.com [329113314678276096]
        Channel: admin-only [330907896982274068]
        Message: .q Hello Adele
09:55:37 MusicPlayer | Starting
09:55:40 MusicPlayer | Get current user
09:55:40 MusicPlayer | Connecting
09:55:42 MusicPlayer | Got Audio client
09:55:42 MusicPlayer | Created pcm stream
```

**Comment by samdivaio** [comment]
Use Docker

**Comment by TheDeadCode** [comment]
Docker won't work btw because you compiled it `docker build...` on windows it seems.

**Comment by TheDeadCode** [comment]
(Different CPU architecture it seems)

**Comment by ryanjmorris** [comment]
Was there any fix on this? Thinking about updating FFMPEG to a more recent version but would that make an issue with compatibility with the bots version? I'm assuming it wouldn't be related.

**Comment by Kwoth** [comment]
You could try... I'm really not sure about centos.

**Comment by borgqueenx** [comment]
I already have ffmpeg at the latest version and the bot is not working.

**Comment by Macley-Kun** [comment]
so do you guys still have the issue? Updated everything to the latest version of FFMPEG and YouTube-dl?

**Comment by LemADEC** [comment]
Using the installer on "CentOS Linux release 7.4.1708 (Core)" broke it further for me:
```
# youtube-dl --version
2017.08.13
# ffmpeg
ffmpeg version 2.6.8 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-4)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --enable-bzlib --disable-crystalhd --enable-gnutls --enable-ladspa --enable-libass --enable-libcdio --enable-libdc1394 --enable-libfaac --enable-nonfree --enable-libfdk-aac --enable-nonfree --disable-indev=jack --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-openal --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libx264 --enable-libx265 --enable-libxvid --enable-x11grab --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-runtime-cpudetect
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 11.102 /  5. 11.102
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
```

```
2017-09-17 14:02:56 (157 MB/s) - ‘nadeko_run.sh’ saved [458/458]


NadekoBot 1.5+
Mirai was here.
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.
Dotnet is not installed. Please install dotnet.
```

```
# youtube-dl
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
# dotnet
bash: dotnet: command not found
# /usr/local/bin/dotnet
Failed to load /opt/dotnet/host/fxr/1.1.0/libhostfxr.so, error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /opt/dotnet/host/fxr/1.1.0/libhostfxr.so)
```

**Comment by Macley-Kun** [comment]
![centos nope](https://user-images.githubusercontent.com/26381427/34321625-e2a925c8-e813-11e7-9a20-479caae76f27.PNG)
![knipsel](https://user-images.githubusercontent.com/26381427/34321626-e2c1b7f0-e813-11e7-8410-cacdbfbd697b.PNG)
Tested this issue out. Things don't rlly seem good from the start. This is a freshly installed CentOS from the same platform i use to host my current bot (what was withoud any issue's).

Just gonna leave this here...

**Comment by Jimmy062006** [comment]
Same here

```0 20:44:50 <GetResolveStrategy>d__2 | Searching for video
0 20:44:51 <GetResolveStrategy>d__2 | Video found
0 20:44:51 <GetResolveStrategy>d__2 | Got stream info
0 20:44:52 MusicPlayer | Starting
0 20:44:52 MusicPlayer | Connecting
0 20:44:52 CommandHandler | Command Executed after 0.007/0.025/1.859s
        User: Jimmy06#0827 [160048078609448961]
        Server: MOFO Central [161913760544456704]
        Channel: music [215927639544692737]
        Message: .play songs

==> /root/.pm2/logs/Nadeko-error-0.log <==
Unrecognized option 'reconnect'.
Error splitting the argument list: Option not found```

**Comment by cyqsimon** [comment]
Same problem here
`0 21:32:54 MusicService | Done creating
0 21:32:54 <GetResolveStrategy>d__2 | Getting link
0 21:32:58 CommandHandler | Command Executed after 0.008/0.033/4.117s
        User: *
        Server: *
        Channel: *
        Message: .play abc
0 21:32:58 MusicPlayer | Starting
0 21:33:02 MusicPlayer | Connecting
Unrecognized option 'reconnect'.
Error splitting the argument list: Option not found
0 21:33:02 VplusTService | Adding role nvoice-448934719053234189 to user [bot]
0 21:33:03 MusicPlayer | Got Audio client
0 21:33:03 MusicPlayer | Created pcm stream
0 21:33:03 MusicPlayer | Song removed because it can't play
0 21:33:03 MusicPlayer | Next song
0 21:33:03 MusicPlayer | Destroying
0 21:33:04 VplusTService | Removing role nvoice-448934719053234189 from user [bot]`

ffmpeg version
`ffmpeg version 2.6.8 Copyright (c) 2000-2016 the FFmpeg developers`

OS version
`centos-release-7-5.1804.el7.centos.2.x86_64`
