### ISSUE TITLE
.lq command returns an error

### ISSUE THREAD

**Issue by XGSleepWalker** [Kwoth/NadekoBot#1361]
CommandHandler | System.FormatException: Input string was not in a correct format.
   at System.Globalization.TimeSpanFormat.FormatCustomized(TimeSpan value, String format, DateTimeFormatInfo dtfi)
   at System.Globalization.TimeSpanFormat.Format(TimeSpan value, String format, IFormatProvider formatProvider)
   at NadekoBot.Modules.Music.Music.<>cDisplayClass11_0.<ListQueue>b0(Int32 curPage)
   at NadekoBot.Extensions.Extensions.<>cDisplayClass10_0.<SendPaginatedConfirmAsync>b0(Int32 x)
   at NadekoBot.Extensions.Extensions.<SendPaginatedConfirmAsync>d11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Music.Music.<ListQueue>d11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.ModuleClassBuilder.<>cDisplayClass6_1.<<BuildCommand>gExecuteCallback1>d.MoveNext()

**Comment by Kwoth** [comment]
Can you post a list of songs that you had when that happens?

**Comment by Kwoth** [comment]
Reopen if it's still happening, nobody else is reporting this.
