### ISSUE TITLE
Music player crashed bot with out of memory errors.

### ISSUE THREAD

**Issue by evacfk** [Kwoth/NadekoBot#1387]
Hi Kwoth, thanks for your time. The bot was playing a playlist then I noticed it stopped, I checked the tmux and saw these errors been displayed over and over. Any idea what could be the cause? I'm on a 512 MB Ram Droplet, Sam said that should be fine and recommended I post here.

Thanks.

`05:46:26 MusicPlayer | Song removed because it can't play
05:46:26 MusicPlayer | Next song
05:46:26 MusicPlayer | Starting
05:46:26 MusicPlayer | System.ComponentModel.Win32Exception: Cannot allocate memory
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NadekoBot.Services.Impl.YtdlOperation.<GetDataAsync>d__2.MoveNext() in /root/NadekoBot/src/NadekoBot/Services/Impl/Ytdl.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Services.Music.SongResolver.Strategies.YoutubeResolveStrategy.<>c__DisplayClass2_0.<<ResolveSong>b__0>d.MoveNext() in /root/NadekoBot/src/NadekoBot/Services/Music/SongResolver/Strategies/YoutubeResolveStrategy.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Services.Music.MusicPlayer.<PlayerLoop>d__98.MoveNext() in /root/NadekoBot/src/NadekoBot/Services/Music/MusicPlayer.cs:line 170`

**Comment by evacfk** [comment]
Another error that came up while playing music tonight, looks like this one also had a mention from the trivia game. It stopped the music from playing but did not crash the bot

'   at Discord.Net.Queue.RequestBucket.<SendAsync>d__18.MoveNext()                                                                                          [9/2041]
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Queue.RequestQueue.<SendAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendInternalAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendJsonAsync>d__59`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<CreateMessageAsync>d__77.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.ChannelHelper.<SendMessageAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.SocketTextChannel.<Discord-IMessageChannel-SendMessageAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Games.Trivia.TriviaGame.<StartGame>d__51.MoveNext() in /root/NadekoBot/src/NadekoBot/Modules/Games/Commands/Trivia/TriviaGame.cs:line 96'

**Comment by Kwoth** [comment]
Hm, this all looks like your server issue. We've been running music for days without memory leaks now.

**Comment by evacfk** [comment]
I was told the digitalocean basic droplet would be sufficient for nadeko. Would you recommend I upgrade? I'm just not sure why this would happen or how I can avoid it.

**Comment by Kwoth** [comment]
Try upgrading. you can resize your droplet and downsize it back later.

**Comment by evacfk** [comment]
Thanks for your time. Feel free to close this. Glad it's not a nadeko issue.

**Comment by Kwoth** [comment]
But keep in mind most people are running it on the cheapest droplet without this issue
