### ISSUE TITLE
No song found. Bot not joining voice channel.

### ISSUE THREAD

**Issue by discrimihate** [Kwoth/NadekoBot#1399]
Having an issue with music. Updated to most recent version that was released a few hours ago. When I type .play or .q followed by a song, it says "song not found". Bot never attempts to join the music room. I have the correct api keys in the json credentials files. 

Any ideas on how to resolve this? I found line 27 where is claims there is an error:
"data = (await ytdl.GetDataAsync(query)).Split('\n');"

ytdl issue?

This is the error that the bot is throwing:
```08:55:50 YoutubeResolveStrategy | System.ComponentModel.Win32Exception: No such file or directory
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NadekoBot.Services.Impl.YtdlOperation.<GetDataAsync>d__2.MoveNext() in /Users/smann/NadekoBot/src/NadekoBot/Services/Impl/Ytdl.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Services.Music.SongResolver.Strategies.YoutubeResolveStrategy.<ResolveSong>d__2.MoveNext() in /Users/smann/NadekoBot/src/NadekoBot/Services/Music/SongResolver/Strategies/YoutubeResolveStrategy.cs:line 27```

**Comment by samdivaio** [comment]
Install Youtube-dl and restart pc

**Comment by discrimihate** [comment]
Fixed without even needing a restart. Just a bot reboot.

Thanks!
