### ISSUE TITLE
Cant restart Nakedo

### ISSUE THREAD

**Issue by traxim** [Kwoth/NadekoBot#1492]
I wanted to update Nakedo bot. i used your guide on the webpage. After the update i wanted to restart nakedo, but everytime it fails by Decompressing at 28%. It says **System.IO.IOException: No space left on device**. And now i cant restart Nakedo bot.

**Comment by Deivedux** [comment]
Well, that message suppose to be self-explanatory, you don't have any space left on your computer as it seems.

**Comment by traxim** [comment]
but i have enough space on my vserver

**Comment by traxim** [comment]
at System.IO.UnixFileStream.WriteCore(Byte[] array, Int32 offset, Int32 count)
   at System.IO.UnixFileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.FileStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at SevenZip.Compression.LZ.OutWindow.Flush()
   at SevenZip.Compression.LZ.OutWindow.CopyBlock(UInt32 distance, UInt32 len)
   at SevenZip.Compression.LZMA.Decoder.Code(Stream inStream, Stream outStream, Int64 inSize, Int64 outSize, ICodeProgress progress)
   at Microsoft.DotNet.Archive.CompressionUtility.Decompress(Stream inStream, Stream outStream, IProgress`1 progress)
   at Microsoft.DotNet.Archive.IndexedArchive.Extract(String compressedArchivePath, String outputDirectory, IProgress`1 progress)
   at Microsoft.DotNet.Configurer.NuGetPackagesArchiver.ExtractArchive()
   at Microsoft.DotNet.Configurer.NuGetCachePrimer.PrimeCache()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
/root/NadekoARN.sh: line 11: 28515 Aborted

**Comment by numbermaniac** [comment]
How much storage space do you have free on your server?

**Comment by Macley-Kun** [comment]
@traxim can you go to your terminal and type in: df -h
We can then see if you have enough space. If you do have enough space i would suggest the following:
Save your credentials.json and your db file that is in the data folder. Try reinstalling Nadeko or perhapes your whole vserver. But i wouldn't say that's needed.

**Comment by Macley-Kun** [comment]
@traxim update? Did you checked the amount of free disk space? Perhapes re-installing the bot again could work?

**Comment by Macley-Kun** [comment]
@traxim can you close this ticket? I assume you cleaned up your system a bit, checked the availabe storage you have now free. And re-install nadeko/re-start the decompressing service/part.
