### ISSUE TITLE
Error then crash

### ISSUE THREAD

**Issue by psewolf** [Kwoth/NadekoBot#15]
I keep getting this when launching the exe, then it crashes:

Google API key provided.
Trello app key provided.
Forwarding messages.
Logging enabled.

Unhandled Exception: System.AggregateException: One or more errors occurred. ---
> System.Net.WebException: The remote server returned an error: (401) Unauthoriz
ed.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar,
Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchron
ization)
--- End of stack trace from previous location where exception was thrown ---
   at Parse.Internal.InternalExtensions.<>c__DisplayClass7`1.<OnSuccess>b__6(Tas
k t)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Parse.Internal.InternalExtensions.<>c__DisplayClass7`1.<OnSuccess>b__6(Tas
k t)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Parse.Internal.InternalExtensions.<>c__DisplayClass7`1.<OnSuccess>b__6(Tas
k t)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Parse.Internal.InternalExtensions.<>c__DisplayClass7`1.<OnSuccess>b__6(Tas
k t)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Parse.Internal.InternalExtensions.<>c__DisplayClass7`1.<OnSuccess>b__6(Tas
k t)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifica
tion)
   at System.Threading.Tasks.Task`1.get_Result()
   at NadekoBot.Commands.ServerGreetCommand..ctor() in C:\Users\Master\Documents
\Visual Studio 2015\Projects\NadekoBot\NadekoBot\Commands\ServerGreetCommand.cs:
line 37
   at NadekoBot.Modules.Administration..ctor() in C:\Users\Master\Documents\Visu
al Studio 2015\Projects\NadekoBot\NadekoBot\Modules\Administration.cs:line 19
   at NadekoBot.NadekoBot.Main() in C:\Users\Master\Documents\Visual Studio 2015
\Projects\NadekoBot\NadekoBot\NadekoBot.cs:line 105

**Comment by Kwoth** [comment]
You must supply proper Parse ID and key credentials. They are mandatory since the last release.
Taken from the readme:  
**For ParseID and ParseKey, you need to register on http://www.parse.com, get those values and create an app with these 3 classes: 'CommandsRan', 'Requests' and 'Stats' in order to make the logging work. **

Here is an image explaining where to find the 2 things you  need.
http://i.imgur.com/bXsL19z.png

If you still have issues, join the nadekolog discord server (link is at the top of the readme)

**Comment by psewolf** [comment]
Awesome! That worked. Thanks!

**Comment by psewolf** [comment]
Will you also push the latest music stability update to the beta release. (the pre-compiled one)

**Comment by Kwoth** [comment]
that means you didn't supply proper bot mention id inside credentials.
Start your bot and do `.uid @Psefwolfbot` copy that id and put it inside <@X> where it says bot mention in the credentials like this: `<@12312332131>`

**Comment by Kwoth** [comment]
here is an image  http://i.imgur.com/Ix22iLY.png

**Comment by psewolf** [comment]
Is there a way to disable the auto response when you PM the bot? I don't want my users knowing all the commands & abusing them.

**Comment by ZR2** [comment]
No only if you are compiling it yourself

**Comment by psewolf** [comment]
Right, what would I change to forgo the 'help PM' function?

**Comment by ZR2** [comment]
Main class

**Comment by Kwoth** [comment]
Please create a new ticket for a new issue. The best way to get answers is to join our discord server
