### ISSUE TITLE
Deleted nadekobot and reinstalled, dotnet always crashes.

### ISSUE THREAD

**Issue by MaybeGoogle** [Kwoth/NadekoBot#1503]
- OSX 10.12.5
- .NET version 1.0.1 (btw your [link](https://www.microsoft.com/net/core#macos) goes to the new 2.0.0 version, not [1.0.1](https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.1-download.md), as NadekoBot requests)

I started installation with `cd /Users/My_Name/Desktop/Programs/Nadeko && wget -N https://github.com/Kwoth/NadekoBot-BashScript/raw/1.4/linuxAIO.sh && bash linuxAIO.sh
`. I used that directory because I like to keep my home directory clean. Everything works well. I download with option 1, add the credentials and the database, and run with option 2. 

All works well (dotnet installed, build succeeded, starting NadekoBot v1.6.4)...

```
Resolving raw.githubusercontent.com... 151.101.0.133, 151.101.0.133
Connecting to raw.githubusercontent.com|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 458 [text/plain]
Saving to: ‘nadeko_run.sh’

nadeko_run.sh                                 100%[==============================================================================================>]     458  --.-KB/s    in 0s

Last-modified header missing -- time-stamps turned off.
2017-08-14 16:17:49 (11.8 MB/s) - ‘nadeko_run.sh’ saved [458/458]


NadekoBot 1.5+
Mirai was here.
Updating to version 2017.08.13 ...
ERROR: no write permissions on /usr/local/bin/youtube-dl (shouldn't matter, don't use music)
Dotnet installed.
  [Stuff about restoring packages]

  NuGet Config files used:
      /Users/My_Name/Desktop/Programs/Nadeko/NadekoBot/src/NadekoBot/NuGet.Config
      /Users/My_Name/Desktop/Programs/Nadeko/NadekoBot/NuGet.Config
      /Users/My_Name/.nuget/NuGet/NuGet.Config

  Feeds used:
      https://api.nuget.org/v3/index.json
      https://www.myget.org/F/kwoth/api/v3/index.json
      https://www.myget.org/F/discord-net/api/v3/index.json
      https://www.myget.org/F/imagesharp/api/v3/index.json
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

  NadekoBot -> /Users/My_Name/Desktop/Programs/Nadeko/NadekoBot/src/NadekoBot/bin/Release/netcoreapp1.1/NadekoBot.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.67
Running NadekoBot. Please wait.
16:18:03 NadekoBot | Starting NadekoBot v1.6.4
16:18:03 NadekoBot | Shard 0 logging in ...
16:18:05 NadekoBot | Shard 0 logged in.
16:18:05 NadekoBot | Shard 0 loading services...
```
... now. At this time, I receive the "dotnet quit unexpectedly." message.
```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: [. Path 'OwnerIds', line 5, position 15.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NadekoBot.Services.Impl.NadekoStrings..ctor(ILocalization loc) in /Users/My_Name/Desktop/Programs/Nadeko/NadekoBot/src/NadekoBot/Services/Impl/NadekoStrings.cs:line 34
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at NadekoBot.Services.NServiceProvider.ServiceProviderBuilder.LoadFrom(Assembly assembly) in /Users/My_Name/Desktop/Programs/Nadeko/NadekoBot/src/NadekoBot/Services/ServiceProvider.cs:line 102
   at NadekoBot.NadekoBot.AddServices() in /Users/My_Name/Desktop/Programs/Nadeko/NadekoBot/src/NadekoBot/NadekoBot.cs:line 132
   at NadekoBot.NadekoBot.<RunAsync>d__43.MoveNext() in /Users/My_Name/Desktop/Programs/Nadeko/NadekoBot/src/NadekoBot/NadekoBot.cs:line 224
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__45.MoveNext() in /Users/My_Name/Desktop/Programs/Nadeko/NadekoBot/src/NadekoBot/NadekoBot.cs:line 274
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Program.Main(String[] args) in /Users/My_Name/Desktop/Programs/Nadeko/NadekoBot/src/NadekoBot/Program.cs:line 16
```
Is this a problem with nadeko 1.6.4? or am I missing something...

**Comment by eruzang** [comment]
Update: upgraded all dependencies using brew. Same problem

**Comment by willysunny** [comment]
(facepalm)

It's your credentials.json.

Double check your OwnerIds and make sure you didn't miss a comma or whatever.

**Comment by MaybeGoogle** [comment]
thats weird, bc i used the exact same credentials.json from before...
anyway, here it is:
```json
  "OwnerIds": [
    312383932870033408
  ],
```

**Comment by willysunny** [comment]
https://jsonformatter.curiousconcept.com 

try copy and paste your entire JSON on a parser like this

If it cannot parse, you know something is wrong.

PS: sometimes the comma before OnwerIds is missing as well, as I said, double check your entire JSON and make sure it's formatted correctly.

**Comment by MaybeGoogle** [comment]
Parsed perfectly...I even used the set up credentials.json option and pasted everything there. nope.

**Comment by MaybeGoogle** [comment]
I did the whole process over, completely, just now, putting things back one at a time, and it worked. I noticed that it is now 1.7, so maybe that is why... anyway, everything is back in place.

**Comment by willysunny** [comment]
I'm guessing you are hosting more than one bot on your comp? then you might be looking at the wrong file the whole time.

**Comment by MaybeGoogle** [comment]
lol willysunny, we've met b4... I'm almost certain it was something wrong with 1.6.4. I've done a clean install of 1.6.4, and a clean install of 1.7, on the same machine. 1.7 worked, 1.6.4 didn't. It's working now, so I'm good.
