### ISSUE TITLE
i cant play song

### ISSUE THREAD

**Issue by alvanos69** [Kwoth/NadekoBot#1504]
06:34:02 YoutubeResolveStrategy | System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at NadekoBot.Services.Impl.YtdlOperation.<GetDataAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Music.Common.SongResolver.Strategies.YoutubeResolveStrategy.<ResolveSong>d__2.MoveNext() 
everytime i link a song it says that

**Comment by willysunny** [comment]
make sure you've installed youtube-dl?

**Comment by Taknok** [comment]
You should see #1053 , and if there isn't any answers post a comment in this section. It seems to be a `youtube-dl` issue as mentioned by willysunny, widely solved in the section.
