### ISSUE TITLE
Issues with Nadekobot 1.8.1, Ubuntu 16.04

### ISSUE THREAD

**Issue by MaybeGoogle** [Kwoth/NadekoBot#1575]
Errors in case you can find anything, with some context:
```Running NadekoBot. Please wait.
23:07:32 NadekoBot | Starting NadekoBot v1.8.1
23:07:32 NadekoBot | Shard 0 logging in ...
23:07:34 NadekoBot | Shard 0 logged in.
23:07:34 NadekoBot | Shard 0 loading services...
23:07:34 NadekoStrings | Loaded 23 languages in 0.07s

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NadekoBot.Modules.Xp.Services.XpService.<>c.<.ctor>b__24_1(GuildConfig x) in /root/NadekoBot/src/NadekoBot/Modules/Xp/Services/XpService.cs:line 85
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at NadekoBot.Modules.Xp.Services.XpService..ctor(CommandHandler cmd, IBotConfigProvider bc, IEnumerable`1 allGuildConfigs, IImagesService images, DbService db, NadekoStrings strings) in /root/NadekoBot/src/NadekoBot/Modules/Xp/Services/XpService.cs:line 82
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at NadekoBot.Services.NServiceProvider.ServiceProviderBuilder.LoadFrom(Assembly assembly) in /root/NadekoBot/src/NadekoBot/Services/ServiceProvider.cs:line 102
   at NadekoBot.NadekoBot.AddServices() in /root/NadekoBot/src/NadekoBot/NadekoBot.cs:line 132
   at NadekoBot.NadekoBot.<RunAsync>d__43.MoveNext() in /root/NadekoBot/src/NadekoBot/NadekoBot.cs:line 224
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__45.MoveNext() in /root/NadekoBot/src/NadekoBot/NadekoBot.cs:line 274
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Program.Main(String[] args) in /root/NadekoBot/src/NadekoBot/Program.cs:line 16
Done

Welcome back to NadekoBot.
Welcome to NadekoBot.
```

some warnings while updating:
```/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning : Detected package downgrade: System.ValueTuple from 4.4.0 to 4.4.0-preview1-25305-02  [/root/NadekoBot/NadekoBot.sln]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  NadekoBot (>= 1.4.1) -> ImageSharp (>= 1.0.0-alpha9-00194) -> System.ValueTuple (>= 4.4.0)  [/root/NadekoBot/NadekoBot.sln]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  NadekoBot (>= 1.4.1) -> System.ValueTuple (>= 4.4.0-preview1-25305-02) [/root/NadekoBot/NadekoBot.sln]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning : Detected package downgrade: System.ValueTuple from 4.4.0 to 4.4.0-preview1-25305-02  [/root/NadekoBot/NadekoBot.sln]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  NadekoBot (>= 1.4.1) -> ImageSharp (>= 1.0.0-alpha9-00194) -> System.ValueTuple (>= 4.4.0)  [/root/NadekoBot/NadekoBot.sln]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): warning :  NadekoBot (>= 1.4.1) -> System.ValueTuple (>= 4.4.0-preview1-25305-02) [/root/NadekoBot/NadekoBot.sln]
```

This happened on updating to 1.8.1; no issues with 1.8 though.
My other selfhost, on OSX (1.8.1 also), doesn't seem to have any issues, but I'm scared to update again and test that.

**Updates**:

OSX was updated again, no problem.

Problem reproduced by BlayzingWhisker#9416 on Ubuntu 16.04

**Update 2**

Definitely a problem: third case on Ubuntu 16.04: !!Deprexxi0n#5337

**Comment by Kwoth** [comment]
How is it null :emiwot:

**Comment by MaybeGoogle** [comment]
gotta be smth from when you were fixing the .xpex User and .xpex Channel thingies... unless you changed something else in the past few hours

**Comment by Kwoth** [comment]
try again now, i pushed an update

**Comment by Kwoth** [comment]
Close if fixed

**Comment by MaybeGoogle** [comment]
Fixed, thanks!
