### ISSUE TITLE
.soundcloudpl problem

### ISSUE THREAD

**Issue by AGNextGen** [Kwoth/NadekoBot#1592]
I wanted to play a soundcloud playlist and i did .souncloudpl https://soundcloud.com/discover/the-upload, but it did not work

So when i checked the NadekoBot log it showed me this 
Plz help 😄 

21:30:00 CommandHandler | Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at NadekoBot.Modules.Music.Music.<SoundCloudPl>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_1.<<BuildCommand>g__ExecuteCallback1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteAsync>d__40.MoveNext()

**Comment by Macley-Kun** [comment]
can it play a normal song just fine?

**Comment by AGNextGen** [comment]
Yes it can play a normal song just fine

**Comment by Macley-Kun** [comment]
And other playlists? Youtube playlists also work fine?
Personnaly i don't use the nadeko music module, so i can't confirm nor deny it.

@Kwoth is this a bug or smth on his end?

**Comment by Macley-Kun** [comment]
#10

**Comment by Macley-Kun** [comment]
#1053 is we’re you have to ask questions about this. I’m sure someone helps you there ok!

**Comment by Kwoth** [comment]
This seems like their api changed. It used to resolve playlists properly before, now when you try to resolve a playlist it returns a 404 url. Very weird..

**Comment by shikhir-arora** [comment]
Is this still an issue? The link provided isn't a playlist, it's a link from the SoundCloud "Discover Tracks" page.

You can make a playlist from those tracks at that page.

Playlists resolve fine: 

https://scapi.nadekobot.me/resolve?url=https://soundcloud.com/shikhir-arora/sets/flow-podcasts

**Comment by Kwoth** [comment]
seems like it got fixed :D
