### ISSUE TITLE
Redis Server issues in 1.9

### ISSUE THREAD

**Issue by halitalf** [Kwoth/NadekoBot#1637]
I'm not real sure what's going on here, but Nadeko fails to load services in 1.9. I tried disabling my firewall without change. 

```
Using launch settings from /home/nadeko/sanctum/NadekoBot/src/NadekoBot/Properties/launchSettings.json...
01:33:32 NadekoBot | Starting NadekoBot v1.9.1
01:33:32 NadekoBot | Shard 0 logging in ...
01:33:33 NadekoBot | Shard 0 logged in.
01:33:33 NadekoBot | Shard 0 loading services...

Unhandled Exception: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 890
   at NadekoBot.Services.Impl.RedisCache..ctor(UInt64 botId) in /home/nadeko/sanctum/NadekoBot/src/NadekoBot/Services/Impl/RedisCache.cs:line 15
   at NadekoBot.NadekoBot.AddServices() in /home/nadeko/sanctum/NadekoBot/src/NadekoBot/NadekoBot.cs:line 145
   at NadekoBot.NadekoBot.<RunAsync>d__43.MoveNext() in /home/nadeko/sanctum/NadekoBot/src/NadekoBot/NadekoBot.cs:line 237
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__45.MoveNext() in /home/nadeko/sanctum/NadekoBot/src/NadekoBot/NadekoBot.cs:line 282
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Program.Main(String[] args) in /home/nadeko/sanctum/NadekoBot/src/NadekoBot/Program.cs:line 16
```

**Comment by Kwoth** [comment]
Did you reinstall prerequisistes? It actually happend to me on one machine. It has nothing to do with firewall.

If you're on linux, just manually install `redis-server` from the command line and try again. I don't know why it happened.

@samdivaio can you check whether maybe 14.04 or some other ubuntu version doesn't have the redis-server line added to the installation script. Because on one machine, i reinstalled prerequisites twice, and redis wasn't installed. I didn't check the OS and the version. But it's ubuntu for sure. `apt-get install redis-server` fixed it.

**Comment by halitalf** [comment]
@Kwoth no, I manually updated the dotnet installation. This explains everything. Reinstalling redis-server.

**Comment by halitalf** [comment]
That fixed it! Sorry about that.

**Comment by halitalf** [comment]
_P.S.: You may want to include that in the [From Source](http://nadekobot.readthedocs.io/en/latest/guides/From%20Source/) doc._

**Comment by samdivaio** [comment]
Can't find it, I can't be sure why it didn't install as it's supposed to, probably related to apt-transport-https package. That means all the music prerequisites failed to install aswell 🤔
