### ISSUE TITLE
Error on building on freshly installed Docker Enviroment

### ISSUE THREAD

**Issue by LitGhostLove** [Kwoth/NadekoBot#1650]
Unhandled Exception: Microsoft.Data.Sqlite.SqliteException: SQLite Error 10: 'disk I/O error'.
   at Microsoft.Data.Sqlite.Interop.MarshalEx.ThrowExceptionForRC(Int32 rc, Sqlite3Handle db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetAppliedMigrations(DatabaseFacade databaseFacade)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetPendingMigrations(DatabaseFacade databaseFacade)
   at NadekoBot.Services.DbService.GetDbContext() in /opt/NadekoBot/src/NadekoBot/Services/DbService.cs:line 28
   at NadekoBot.NadekoBot..ctor(Int32 shardId, Int32 parentProcessId, Nullable`1 port) in /opt/NadekoBot/src/NadekoBot/NadekoBot.cs:line 86
   at NadekoBot.Program.Main(String[] args) in /opt/NadekoBot/src/NadekoBot/Program.cs:line 15

Platform: Windows 10 x64 Home Edition
Tool: Docker Toolbox 17.07.0-ce

**Comment by Kwoth** [comment]
Oh, you're on windows, that docker is for unix environments. I believe there's a difference between them (I may be completely wrong here)

**Comment by Macley-Kun** [comment]
Whose docker do you use? Also, have you first tried installing and running nadeko normally on your computer?

Unrelated question?: why you want to run NadekoBot in a docker?

**Comment by Kwoth** [comment]
@Poag sorry for the ping, are we able to use the image you created on docker for windows or not?

**Comment by Poag** [comment]
Shouldn't make any difference, it takes everything it needs with the container.

They appearing to be having an issue reading from disk on the local device. So it would appear docker doesn't have rights into windows to r/w the local filesystem.


But its windows so...why would you run the docker there? I'd go as far to say its actually inadvisable to run it in windows.
