### ISSUE TITLE
Nadeko dosent Work on one Specific Server

### ISSUE THREAD

**Issue by AmelieXx** [Kwoth/NadekoBot#1660]
Nadeko refuses to work on one Server while it works on every onther Server. Even the Public Nadeko refuses to work on it when i tested it so its not an Problem in selfhosting

16:11:25 CommandHandler | Error in CommandHandler
16:11:25 CommandHandler | System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.WebSocket.SocketGuildChannel.GetPermissionOverwrite(IRole role)
   at Discord.Permissions.ResolveChannel(IGuild guild, IGuildUser user, IGuildChannel channel, UInt64 guildPermissions)
   at Discord.WebSocket.SocketTextChannel.<get_Users>b__13_0(SocketGuildUser x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Discord.WebSocket.SocketTextChannel.get_Users()
   at Discord.WebSocket.SocketGuildChannel.Discord.IChannel.GetUsersAsync(CacheMode mode, RequestOptions options)
   at Discord.Commands.UserTypeReader`1.<Read>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.ParameterInfo.<Parse>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandParser.<ParseArgs>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ParseAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Services.CommandHandler.<ExecuteCommand>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Services.CommandHandler.<TryRunCommand>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Services.CommandHandler.<MessageReceivedHandler>d__46.MoveNext()

**Comment by Kwoth** [comment]
tracked here #1535
