### ISSUE TITLE
.hentai command doesn't work after setting blacklist with .nsfwtagbl

### ISSUE THREAD

**Issue by CRUSTAAY** [Kwoth/NadekoBot#1661]
steps to reproduce error:

1. use `.hentai` command, verify that the command works
2. use `.nsfwtbl yaoi` or another tag
3. use '.hentai' command, the console should output the error below, and provide no lewds :(
4. use the same command in step 2 to remove the blacklisted tag
5. use `.hentai` again, `.hentai` should work as normal

OS: Ubuntu 16.04.3 LTS
Bot: NadekoBot v1.10.2
installed today following linux docs guide

The following is the output in the console
note: removed personal details such as server/user/linuxuser details with [removed] 
```
00:05:35 CommandHandler | Command Executed after 0/0/0.472s
        User: [removed]
        Server: [removed]
        Channel: l-lewds [removed]
        Message: .nsfwtagbl
00:05:46 CommandHandler | System.NullReferenceException: Object reference not set to an instance of an object.
   at NadekoBot.Modules.Searches.Services.SearchesService.<>c__DisplayClass31_0.<DapiSearch>b__0(String x) in /home/[removed]/NadekoBot/src/NadekoBot/Modules/Searches/Services/SearchesService.cs:line 143
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at NadekoBot.Modules.Searches.Services.SearchesService.DapiSearch(String tag, DapiSearchType type, Nullable`1 guild, Boolean isExplicit) in /home/[removed]/NadekoBot/src/NadekoBot/Modules/Searches/Services/SearchesService.cs:line 142
   at NadekoBot.Modules.NSFW.NSFW.<InternalHentai>d__4.MoveNext() in /home/[removed]/NadekoBot/src/NadekoBot/Modules/NSFW/NSFW.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_1.<<BuildCommand>g__ExecuteCallback1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteAsync>d__40.MoveNext()
00:05:46 CommandHandler | Command Executed after 0/0/0.028s
        User: [removed]
        Server: [removed]
        Channel: l-lewds [removed]
        Message: .hentai
```

**Comment by Kwoth** [comment]
Fixed in 2.0
