### ISSUE TITLE
issue when i launch the bot

### ISSUE THREAD

**Issue by tetzispa** [Kwoth/NadekoBot#1662]
hello !

i have this issue on Debian Jessie (64 bits) when i launch the bot :  

```
Unhandled Exception: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 890
   at NadekoBot.Services.Impl.RedisCache..ctor(UInt64 botId) in /root/NadekoBot/src/NadekoBot/Services/Impl/RedisCache.cs:line 15
   at NadekoBot.NadekoBot.AddServices() in /root/NadekoBot/src/NadekoBot/NadekoBot.cs:line 145
   at NadekoBot.NadekoBot.<RunAsync>d__43.MoveNext() in /root/NadekoBot/src/NadekoBot/NadekoBot.cs:line 237
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__45.MoveNext() in /root/NadekoBot/src/NadekoBot/NadekoBot.cs:line 282
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Program.Main(String[] args) in /root/NadekoBot/src/NadekoBot/Program.cs:line 16
Done
```

how can i fix it ? i have no errors when i launch it : 

youtube-dl is up-to-date (2017.09.24)
    0 Warn(s)
    0 Error(s)

Temps écoulé 00:00:05.57

18:12:32 NadekoBot | Starting NadekoBot v1.10.2
18:12:32 NadekoBot | Shard 0 logging in ...
18:12:34 NadekoBot | Shard 0 logged in.
18:12:34 NadekoBot | Shard 0 loading services...

and the error appears

thx a lot for your help/answer

**Comment by sleepymanakete** [comment]
Install Redis, if you're on Windows download from the updater (make sure you have the lastest updater)
![image](https://user-images.githubusercontent.com/30272172/31047450-42a9c54c-a5c8-11e7-9144-8d44925d9025.png)

**Comment by tetzispa** [comment]
wow ! thx ! they should write on tutorial !
