### ISSUE TITLE
Issue after updating.

### ISSUE THREAD

**Issue by izelman** [Kwoth/NadekoBot#1671]
I love using this bot, and now I feel kind of lost without it. Whenever I launch the bot I get this. 

21:37:46 NadekoBot | Starting NadekoBot v1.10.2
21:37:46 NadekoBot | Shard 0 logging in ...
21:37:47 NadekoBot | Shard 0 logged in.
21:37:47 NadekoBot | Shard 0 loading services...

Unhandled Exception: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 890
   at NadekoBot.Services.Impl.RedisCache..ctor(UInt64 botId)
   at NadekoBot.NadekoBot.AddServices()
   at NadekoBot.NadekoBot.<RunAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Program.Main(String[] args)

**Comment by xnaas** [comment]
Did you install Redis?

**Comment by izelman** [comment]
I did, but that wasn't what fixed it. I just re-installed
It works now
