### ISSUE TITLE
crash at startup  (redis issues ?)

### ISSUE THREAD

**Issue by etshy** [Kwoth/NadekoBot#1677]
HI
To update my biot I completely delete dotnet and nadeko, and reinstalled them both.

dotnet is well installed (I had to install it 3 times to be working but that's good)
and now I have these exceptions

23:34:00 NadekoBot | Starting NadekoBot v1.10.2
23:34:00 NadekoBot | Shard 0 logging in ...
23:34:02 NadekoBot | Shard 0 logged in.
23:34:02 NadekoBot | Shard 0 loading services...

Unhandled Exception: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 890
   at NadekoBot.Services.Impl.RedisCache..ctor(UInt64 botId) in /root/NadekoBot/src/NadekoBot/Services/Impl/RedisCache.cs:line 15
   at NadekoBot.NadekoBot.AddServices() in /root/NadekoBot/src/NadekoBot/NadekoBot.cs:line 145
   at NadekoBot.NadekoBot.<RunAsync>d__43.MoveNext() in /root/NadekoBot/src/NadekoBot/NadekoBot.cs:line 237
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__45.MoveNext() in /root/NadekoBot/src/NadekoBot/NadekoBot.cs:line 282
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Program.Main(String[] args) in /root/NadekoBot/src/NadekoBot/Program.cs:line 16
Done

I didn't know redis was required ?

**Comment by Kwoth** [comment]
#1674

**Comment by etshy** [comment]
I don't have the install redis option witht he installer from the tuto
```cd ~ && wget -N https://github.com/Kwoth/NadekoBot-BashScript/raw/1.9/linuxAIO.sh && bash linuxAIO.sh```
and the  Auto-Install Prerequisites option didn't install it

And I don't find any .sh in my NadekoBot folder.

Do I need to install redis next to Nadeko, and you have a script to install it properly with nadeko ?

**Comment by Kwoth** [comment]
#1664

**Comment by etshy** [comment]
Oh I missed that one when I searched.

Thanks a lot.
