### ISSUE TITLE
Error when running Systemd

### ISSUE THREAD

**Issue by Macley-Kun** [Kwoth/NadekoBot#1680]
I've bin working to get nadeko working on Systemd. But i notice this re-occuring problem:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
at System.IO.Path.Combine(String path1, String path2)
at Microsoft.DotNet.Configurer.CliFallbackFolderPathCalculator.get_DotnetUserProfileFolderPath()
at Microsoft.DotNet.Configurer.FirstTimeUseNoticeSentinel..ctor(CliFallbackFolderPathCalculatorcliFallbackFolderPathCalculator)
at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

Running nadeko runs normally perfect. Just with a service file it returns this strangely.

**Comment by Kwoth** [comment]
No idea.

**Comment by Macley-Kun** [comment]
lmao

**Comment by shikhir-arora** [comment]
@Macley-Kun

Just run it with pm2. you’ll accomplish the same thing. use this if you want: https://gist.github.com/shikhir-arora/b1ec4820e3299c255e4f97dcfdf99d87

**Comment by Macley-Kun** [comment]
@shikhir-arora Dude thank you so much! it's the perfect solution to run nadeko!

**Comment by shikhir-arora** [comment]
@Macley-Kun Glad it worked, been using that for a few months myself.

**Comment by Macley-Kun** [comment]
@Skyrid3r
You can close your feature now, you can instead use this right now!
