### ISSUE TITLE
Nadeko instantly crashing

### ISSUE THREAD

**Issue by EpikIMMORTAL** [Kwoth/NadekoBot#1686]
22:28:51 NadekoBot | Starting NadekoBot v1.10.2
22:28:51 NadekoBot | Shard 0 logging in ...
22:28:52 NadekoBot | Shard 0 logged in.
22:28:52 NadekoBot | Shard 0 loading services...

Unhandled Exception: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 890
   at NadekoBot.Services.Impl.RedisCache..ctor(UInt64 botId)
   at NadekoBot.NadekoBot.AddServices()
   at NadekoBot.NadekoBot.<RunAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Program.Main(String[] args)

The error has continually popping up

**Comment by anonymasen** [comment]
do you have Redis installed?

**Comment by EpikIMMORTAL** [comment]
Yes

**Comment by EpikIMMORTAL** [comment]
I am still getting the same error but the nadako updater is telling me I dont have redis installed, and when I try to install it it is telling me that to make sure I have sufficient privileges

**Comment by xnaas** [comment]
Are you running the latest Nadeko installer as Admin?

**Comment by EpikIMMORTAL** [comment]
I do believe so

**Comment by EpikIMMORTAL** [comment]
Got it. Was a problem with the redis. Deleted the files and reinstalled it and it is working
