### ISSUE TITLE
Cannot uninstall?

### ISSUE THREAD

**Issue by CloysterOyster** [Kwoth/NadekoBot#1687]
Every time I go to uninstall I get this https://i.imgur.com/ryHM1sy.png and then nothing happens.
I deleted every file I could find of NadekoBot.
When I go to launch the setup I get this https://i.imgur.com/ACzP6Nl.png

Clicked on Details and got this:

SOURCES
	Deployment url			: https://dl.nadekobot.me/NadekoUpdater.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of https://dl.nadekobot.me/NadekoUpdater.application resulted in exception. Following failure messages were detected:
		+ The referenced assembly is not installed on your system. (Exception from HRESULT: 0x800736B3)

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [10/5/2017 12:43:23 PM] : Activation of https://dl.nadekobot.me/NadekoUpdater.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [10/5/2017 12:43:33 PM] System.Runtime.InteropServices.COMException
		- The referenced assembly is not installed on your system. (Exception from HRESULT: 0x800736B3)
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Internal.Isolation.IStore.GetAssemblyInformation(UInt32 Flags, IDefinitionIdentity DefinitionIdentity, Guid& riid)
			at System.Deployment.Internal.Isolation.Store.GetAssemblyManifest(UInt32 Flags, IDefinitionIdentity DefinitionIdentity)
			at System.Deployment.Application.ComponentStore.GetAssemblyManifestFromStore(DefinitionIdentity asmId)
			at System.Deployment.Application.ComponentStore.GetAssemblyManifestWithRetry(DefinitionIdentity asmId, TimeSpan retryInterval, Int32 maxRetryCount)
			at System.Deployment.Application.ComponentStore.GetSubscriptionStateInternal(DefinitionIdentity subId)
			at System.Deployment.Application.SubscriptionStore.GetSubscriptionStateInternal(SubscriptionState subState)
			at System.Deployment.Application.SubscriptionStore.CheckAndReferenceApplication(SubscriptionState subState, DefinitionAppId appId, Int64 transactionId)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by Macley-Kun** [comment]
You tried installing Nadeko, and then uninstalling it trough Control Panel (or CCleaner?)

**Comment by CloysterOyster** [comment]
@Macley-Kun Have not tried CCleaner actually, let me give that a shot.

**Comment by Macley-Kun** [comment]
Strange, so even if you install it back, and delete it afterwards just the same errors occure?
The only other way you can do it is just manually delete everything i guess. There's not much else you can do.

**Comment by CloysterOyster** [comment]
@Macley-Kun I cant even run the setup, I get the error message shown in the main post. I don't know where else nadeko files are located as I think I've deleted them all

**Comment by Kwoth** [comment]
https://github.com/Kwoth/NadekoBot/issues/1651 try this (my last post)

**Comment by CloysterOyster** [comment]
@Kwoth Deleted from Registry, went to 'Add or Remove Programs' to uninstall and did the same thing, still can't uninstall. Super confused

**Comment by Macley-Kun** [comment]
@CloysterOyster your still having this strange issue?

**Comment by Macley-Kun** [comment]
This issue can be closed, OP hasn't responded in 17 days.
Solution: use any third party removal tool, try to re-install or maybe install in a different directory.

**Comment by Macley-Kun** [comment]
@CloysterOyster @Kwoth no respons after a week, think it's safe to say to close this one :-)

**Comment by Macley-Kun** [comment]
Someone please close this issue. @Kwoth @CloysterOyster
