### ISSUE TITLE
Attempting to Self-Host: NadekoBot crashes on startup

### ISSUE THREAD

**Issue by TrevorIrion** [Kwoth/NadekoBot#1695]
I've followed the guide to a T and have set up the credentials.json correctly as far as I know. I've updated to the latest version yet when I try to run the bot this happens:

18:57:48 NadekoBot | Starting NadekoBot v1.10.2
18:57:48 NadekoBot | Shard 0 logging in ...
18:57:50 NadekoBot | Shard 0 logged in.
18:57:50 NadekoBot | Shard 0 loading services...

Unhandled Exception: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 890
   at NadekoBot.Services.Impl.RedisCache..ctor(UInt64 botId)
   at NadekoBot.NadekoBot.AddServices()
   at NadekoBot.NadekoBot.<RunAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Program.Main(String[] args)

**Comment by Kwoth** [comment]
#1677
#1686
