### ISSUE TITLE
Nadeko Won't Start Up?

### ISSUE THREAD

**Issue by NoxVeritas** [Kwoth/NadekoBot#1698]
Went through all the steps on the guide but have been getting this message when I start up:

```
11:47:46` NadekoBot | Starting NadekoBot v1.10.2
11:47:46 NadekoBot | Shard 0 logging in ...
11:47:47 NadekoBot | Shard 0 logged in.
11:47:47 NadekoBot | Shard 0 loading services...

Unhandled Exception: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 890
   at NadekoBot.Services.Impl.RedisCache..ctor(UInt64 botId)
   at NadekoBot.NadekoBot.AddServices()
   at NadekoBot.NadekoBot.<RunAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Program.Main(String[] args)
```

I had Nadeko running at one point but uninstalled and this is what

**Comment by Kwoth** [comment]
#1677
#1686

**Comment by NoxVeritas** [comment]
@Kwoth Sorry to bother but is this the correct link to install redis on a windows machine? https://redis.io/download 

It seems like all the other people having this issue weren't using windows and additionally on the website linked for redis, it says that it doesn't technically support windows so I'm still a bit confused. 

Thanks in advance.

**Comment by xnaas** [comment]
@NoxVeritas is you're on Windows, if you just use the installer, there's a button to install redis.

![img](https://i.imgur.com/MK8Km9F.png)

**Comment by NoxVeritas** [comment]
Thanks for the help :) !

**Comment by xnaas** [comment]
If this is solved, you should close it. 😉 

Should be a "close" or "comment and close" button. 😄

**Comment by shivaco** [comment]
Install Redis, it is in bottom corner of NadekoBot Updater
