### ISSUE TITLE
.prune [value] does not work in one server.

### ISSUE THREAD

**Issue by MaybeGoogle** [Kwoth/NadekoBot#1706]
Tested with 2 selfhosts and public nadekobot. Both selfhosts have the same error when trying to prune. 

```17:16:28 CommandHandler | Error in CommandHandler
17:16:28 CommandHandler | System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.WebSocket.SocketGuildChannel.GetPermissionOverwrite(IRole role)
   at Discord.Permissions.ResolveChannel(IGuild guild, IGuildUser user, IGuildChannel channel, UInt64 guildPermissions)
   at Discord.WebSocket.SocketTextChannel.<get_Users>b__13_0(SocketGuildUser x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Discord.WebSocket.SocketTextChannel.get_Users()
   at Discord.WebSocket.SocketGuildChannel.Discord.IChannel.GetUsersAsync(CacheMode mode, RequestOptions options)
   at Discord.Commands.UserTypeReader`1.<Read>d__0.MoveNext()
```

Ubuntu 16.04 and OSX
v1.10.12

Happened between 3 AM UTC and 5 AM UTC on 10/11/17, without an update or restart
Server ID: 273572648519204866

Stuff that probably doesn't matter:

- Reinstalled the one on linux
- Got new token for one on linux
- Another bot is running on that same linux machine. Other bot works. Putting the token into the other bot also works.

**Comment by Kwoth** [comment]
tracked #1535
