### ISSUE TITLE
can not run the nadeko.exe

### ISSUE THREAD

**Issue by chuotrangho** [Kwoth/NadekoBot#1709]
i try do after this http://nadekobot.readthedocs.io/en/latest/JSON%20Explanations/ 
and after that i try to run the nadekoBot.exe that I get this 🥇 

 Unhandled Exception: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 890
   at NadekoBot.Services.Impl.RedisCache..ctor(UInt64 botId)
   at NadekoBot.NadekoBot.AddServices()
   at NadekoBot.NadekoBot.<RunAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Program.Main(String[] args)

![nadekobot](https://user-images.githubusercontent.com/32727486/31481216-6cbe67f6-af4c-11e7-8018-d9f4315efac3.jpg)

Can i ask how to fix this issues,i trust try to use music with my  friend in discord but it say server busy so i have to host it

**Comment by Kyousei** [comment]
You need to Install Redis.


Open your NadekoBot Updater, then on the bottom, there's a `Install Redis` button.
Click it and complete the Redis installation wizard.
Once Redis is installed, restart your bot.
