### ISSUE TITLE
Nadeko Crash on Startup

### ISSUE THREAD

**Issue by Eleqtra** [Kwoth/NadekoBot#1718]
Hello. I've been running Nadeko on my server for a few weeks then decided not to respond. I had restarted it but not getting any response from the bot even though it showed online. I then opened the launcher and updated the bot. When I restarted the bot, it showed with this message then the window stopped responding. I don't really understand how to fix this issue and have been looking through other threads and FAQs. Is there any way to fix this issue?

------------------------------------------------------

22:41:08 NadekoBot | Starting NadekoBot v1.10.2
22:41:08 NadekoBot | Shard 0 logging in ...
22:41:10 NadekoBot | Shard 0 logged in.
22:41:10 NadekoBot | Shard 0 loading services...

Unhandled Exception: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 890
   at NadekoBot.Services.Impl.RedisCache..ctor(UInt64 botId)
   at NadekoBot.NadekoBot.AddServices()
   at NadekoBot.NadekoBot.<RunAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Program.Main(String[] args)

**Comment by shivaco** [comment]
Install Redis (left bottom corner in the installer), restart your PC, and then, start the bot
