### ISSUE TITLE
.shardstats-related redis issue(?)

### ISSUE THREAD

**Issue by QuantumToasted** [Kwoth/NadekoBot#1744]
This doesn't seem to affect anything from what I can tell, but I seem to get this every time shortly after I start my bot. `.shardstats` looks normal, however.

```cs
20:18:10 ShardsCoordinator | StackExchange.Redis.RedisTimeoutException: Timeout performing LRANGE MzcxMTMzMD_shardstats, inst: 1, queue: 1, qu: 0, qs: 1, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: , serverEndpoint: 127.0.0.1:6379, keyHashSlot: 13979 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2120
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
   at StackExchange.Redis.RedisDatabase.ListRange(RedisKey key, Int64 start, Int64 stop, CommandFlags flags) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 874
   at NadekoBot.Core.Services.ShardsCoordinator.<>c__DisplayClass16_0.<<RunAsync>b__1>d.MoveNext()

````

**Comment by Kwoth** [comment]
Try restarting your server?
