### ISSUE TITLE
NadekoBot Stops Working After 5 Seconds

### ISSUE THREAD

**Issue by RealSmecks** [Kwoth/NadekoBot#1755]
I wanted to run NadekoBot on my system but this is what I get when launching the .exe with administrator permissions. 

I am running Windows 10, 64 bit. NadekoBot version is v1.10.2. Please help me. I have read the help files etc, but still won't work.

14:41:36 NadekoBot | Starting NadekoBot v1.10.2
14:41:36 NadekoBot | Shard 0 logging in ...
14:41:38 NadekoBot | Shard 0 logged in.
14:41:38 NadekoBot | Shard 0 loading services...

Unhandled Exception: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 890
   at NadekoBot.Services.Impl.RedisCache..ctor(UInt64 botId)
   at NadekoBot.NadekoBot.AddServices()
   at NadekoBot.NadekoBot.<RunAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Program.Main(String[] args)

**Comment by Deivedux** [comment]
You need to install Redis via your Nadeko Updater, it's a small button which can be found on the bottom-left side of the app. If it still won't work then try to restart your bot and see if that helped.
