### ISSUE TITLE
.poll is broken again

### ISSUE THREAD

**Issue by willysunny** [Kwoth/NadekoBot#1756]
as subject.

All votes / .pollstats / .pollend would spew out errors like no tomorrow

**Comment by MaybeGoogle** [comment]
there aren't really that many errors... but yea i can confirm that it doesn't work. 

`.pollend`:
```23:46:33 CommandHandler | System.NullReferenceException: Object reference not set to an instance of an object.
   at NadekoBot.Modules.Games.Games.PollCommands.<Pollend>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_1.<<BuildCommand>g__ExecuteCallback1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
After that the command handler says that the command has been executed, but nothing appears in the channel.

**Comment by Kwoth** [comment]
Nope, works fine for me. Make sure you've updated. I fixed a few bugs 2 days ago
