### ISSUE TITLE
.feed Command Fails to work with feeds that use .xml feeds; throws Unknown Rss Feed error

### ISSUE THREAD

**Issue by StarlightGalerie** [Kwoth/NadekoBot#1772]
My friend, the owner of a server, tried to use my self-hosted Nadeko to set up a feed utilizing Steam News' feed, which is in the forme of a .xml. Instead of accepting the link, the feed parser tried to pass off the requested link as an Rss and threw an XmlException instead. The command and link are shown below the thrown exception for demonstration.

> System.Xml.XmlException: Unknown Rss Feed
   at Microsoft.SyndicationFeed.Rss.RssFeedReader.<InitRead>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SyndicationFeed.Rss.RssFeedReader.<Read>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Searches.Searches.FeedCommands.<Feed>d__2.MoveNext()
14:48:34 CommandHandler | Command Executed after 0/0/0.422s
        User: SP33D#8631 [192303473478467584]
        Server: Gamez [225661388528287744]
        Channel: staff [364085727996149762]
        Message: .feed http://store.steampowered.com/feeds/news.xml

**Comment by arxkr** [comment]
https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fstore.steampowered.com%2Ffeeds%2Fnews.xml
I don't know how ms wrote their reader, but w3 doesn't like it. Maybe rebuilding it yourself with a different parser will yield success...

**Comment by Kwoth** [comment]
#1628 we'll track it here
