### ISSUE TITLE
The bot crashes on startup

### ISSUE THREAD

**Issue by JesterguyNZ** [Kwoth/NadekoBot#1796]
So recently I got around to updating the bot and now I've been getting this error. I'd appreciate if I got a solution to this problem.
-------------------------------------------------------------------------------------------------------------------
`Unhandled Exception: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func 1 multiplexerFactory, TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 890
   at NadekoBot.Core.Services.ShardsCoordinator..ctor()
   at NadekoBot.Program.Main(String[] args)
   at NadekoBot.Program.<Main>(String[] args)`

**Comment by MaybeGoogle** [comment]
Open NadekoBot Updater and click Install Redis.
If there's no Install Redis button, restart NadekoBot Updater, then try again.
Once the Redis is installed, restart your bot.

This is from one of the pins in #help channel for NadekoLog. If you still have issues, go there.

**Comment by JesterguyNZ** [comment]
Well it's always good to know that I'm blind.
