### ISSUE TITLE
How to fix? 

### ISSUE THREAD

**Issue by plan291037** [Kwoth/NadekoBot#1797]
Error whan start.
```
Unhandled Exception: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 890
   at NadekoBot.Core.Services.ShardsCoordinator..ctor()
   at NadekoBot.Program.Main(String[] args)
   at NadekoBot.Program.<Main>(String[] args)
```

**Comment by shikhir-arora** [comment]
![c05478ab-cc78-4f8f-a281-02d8b807dde9](https://user-images.githubusercontent.com/8797918/32400877-6430d0fa-c0dc-11e7-8db6-8aa4a15dc202.jpeg)
