### ISSUE TITLE
On music play bot join and after half second leave voice

### ISSUE THREAD

**Issue by CikerDeveloper** [Kwoth/NadekoBot#1812]
Im using ubuntu 14.04 here is screenshot from vps https://i.imgur.com/jRKyMaR.png
Here is error message

```
0 17:23:42 ConverterService | Ignore the message below
0 17:23:42 ConverterService | System.Net.Http.HttpRequestException: Response status code does not indicate success: 504 (Gateway Time-out).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.<GetStringAsyncCore>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Utility.Services.ConverterService.<GetCurrencyRates>d__9.MoveNext() in /root/NadekoBot/NadekoBot.Core/Modules/Utility/Services/ConverterService.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Utility.Services.ConverterService.<UpdateCurrency>d__10.MoveNext() in /root/NadekoBot/NadekoBot.Core/Modules/Utility/Services/ConverterService.cs:line 62

```

**Comment by Macley-Kun** [comment]
@CikerDeveloper we got a separate issue for that:#1053
Ask there please. Close this one.

**Comment by Kwoth** [comment]
This error message has nothing to do with the issue you're describing.
