### ISSUE TITLE
.feed/.feedadd Issues...

### ISSUE THREAD

**Issue by NGPriest** [Kwoth/NadekoBot#1834]
https://www.reddit.com/r/Ingress/.rss

> Invalid link, or you're already following that feed on this server, or you've reached maximum number of feeds allowed.

```
System.Xml.XmlException: Unknown Rss Feed
   at Microsoft.SyndicationFeed.Rss.RssFeedReader.<InitRead>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SyndicationFeed.Rss.RssFeedReader.<Read>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Searches.Searches.FeedCommands.<Feed>d__2.MoveNext() in /home/ngpriest/NadekoBot/NadekoBot.Core/Modules/Searches/FeedCommands.cs:line 42```

**Comment by MaybeGoogle** [comment]
Follow all the messy rss stuff in #1628 
Reddit's rss not working is known, #1801
