### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by itsMaxra** [Kwoth/NadekoBot#1851]
every time i launch nadeko it crashes here ... i installed every and version 2.5.2 ![screenshot_527](https://user-images.githubusercontent.com/33780640/32979575-3a172c1c-cc60-11e7-94fd-5e98b9d40d74.png)
thing
![screenshot_526](https://user-images.githubusercontent.com/33780640/32979571-20dad082-cc60-11e7-981d-465190bdf4cc.png)

**Comment by itsMaxra** [comment]
![screenshot_531](https://user-images.githubusercontent.com/33780640/32980106-53871636-cc69-11e7-806f-a96ed146ff42.png)

**Comment by Macley-Kun** [comment]
Try to remove Nadeko from you computer, but backup your database and credentials.json.
If you install her again and see if you still have the issue. :-)

**Comment by itsMaxra** [comment]
This is the first startup

**Comment by Macley-Kun** [comment]
Can you try to update again? I'm still thinking for a solution for this.. Maybe support can help you a bit with this one..

**Comment by samdivaio** [comment]
Is that Windows 7?

**Comment by Macley-Kun** [comment]
@itsMaxra ya still having this issue? Were wondering if your using an unsupported version.

**Comment by itsMaxra** [comment]
@Macley-Kun yes im using windows 8.1 latest update

**Comment by Macley-Kun** [comment]
Try re-installing nadeko completely. Also maybe turn off your firewall and anti-virus just to be sure.

**Comment by Macley-Kun** [comment]
did it worked @itsMaxra ?

**Comment by Paril** [comment]
Same issue here. 

```Unhandled Exception: Discord.Net.HttpException: The server responded with error 401: 401: Unauthorized
   at Discord.Net.Queue.RequestBucket.<SendAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Queue.RequestQueue.<SendAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendInternalAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendAsync>d__57`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<GetVoiceRegionsAsync>d__142.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.DiscordSocketClient.<OnLoginAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<LoginAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Program.<Main>(String[] args)```

**Comment by Paril** [comment]
I have figured it out. Chances are the OP was like me and put the bot's secret in the Token field and not the bot user's Token. Sorry about that!

**Comment by Macley-Kun** [comment]
Thanks for sharing your solution @Paril! @itsMaxra can you check if the above solution can help you out too?

**Comment by itsMaxra** [comment]
Well I'll probably try it but it's to difficult right now because I'm in hospital and I will be available at Saturday Thanks !

**Comment by Macley-Kun** [comment]
@itsMaxra i hope everything is ok with you health! Just reply to the issue when you've tried it :-)

**Comment by itsMaxra** [comment]
Yeah thanks ! :-)

**Comment by Macley-Kun** [comment]
Hey dude got an update on your issue? Did it worked out?

**Comment by itsMaxra** [comment]
Oh sorry I forgot to reply yeah its working finally :-)

**Comment by itsMaxra** [comment]
You can close it now and thanks for the support everyone

**Comment by itsMaxra** [comment]
Oh you are right and happy holidays to you and your family and thanks
