### ISSUE TITLE
No module named 'youtube_dl'

### ISSUE THREAD

**Issue by yaitsbilly** [Kwoth/NadekoBot#1858]
With in the updater I'll clicked installed youtuibe-dl and it says it is, I can see the folder under my C drive. I've even tried downloading it off there side and doing --update command.

0 16:15:59 <ResolveSong>d__2 | Traceback (most recent call last):
  File "c:\users\xxxxx\appdata\local\programs\python\python35-32\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\xxxxx\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python35-32\Scripts\youtube-dl.exe\__main__.py", line 5, in <module>
ImportError: No module named 'youtube_dl'

**Comment by yaitsbilly** [comment]
Fixed by uninstalling Python 3.5 an install 3.6
