### ISSUE TITLE
weather problem

### ISSUE THREAD

**Issue by SillyBirds** [Kwoth/NadekoBot#1861]
Hey, it's me again. Is there currently a problem with `.we`?

```0 13:03:03 CommandHandler | System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.<GetStringAsyncCore>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Searches.Searches.<Weather>d__18.MoveNext() in /home/bakatsuki/NadekoBot/NadekoBot.Core/Modules/Searches/Searches.cs:line 157
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_1.<<BuildCommand>g__ExecuteCallback1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteAsync>d__40.MoveNext()
0 13:03:03 CommandHandler | Command Executed after 0/0/0.072s
        User: RS#4150 [167986054165561344]
        Server: The Ginrei Rocket [170620849823416320]
        Channel: general [170620849823416320]
        Message: .we nyc, us
```

**Comment by shikhir-arora** [comment]
Yeah it does that when the location couldn't be found/parsed. So `.we nyc, us` won't work but it works fine if you do `.we New York` (since NYC is a big city) or `.we New York, US` or `.we New York City` or any other valid result.

**Comment by SillyBirds** [comment]
I hadn't used `.we` in a while, but at lest a few weeks back, it worked fine using just nyc; that's why I was asking.

**Comment by Kwoth** [comment]
Yea it should show a user friendly-error

**Comment by SillyBirds** [comment]
There was no response by the bot, other than the console error.

**Comment by shikhir-arora** [comment]
Yeah can confirm there’s no error message present.

**Comment by Macley-Kun** [comment]
So what are the next steps? Do we ask for help to make a friendly-error? Or are you gonna pick this up @Kwoth ?

**Comment by Kwoth** [comment]
I added it several days ago, forgot to close the issue.
