### ISSUE TITLE
Cannot delete custom reactions.

### ISSUE THREAD

**Issue by harsha1306** [Kwoth/NadekoBot#1866]
Hi when I try to delete a custom reaction from the bot I get the following error in my console:
```
0 17:25:01 CommandHandler | StackExchange.Redis.RedisConnectionException: UnableToResolvePhysicalConnection on PUBLISH                                                                                                                
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.CustomReactions.CustomReactions.<DelCustReact>d__11.MoveNext() in /home/harsha1306/NadekoBot/NadekoBot.Core/Modules/CustomReactions/CustomReactions.cs:line 292                                               
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_1.<<BuildCommand>g__ExecuteCallback1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternal>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteAsync>d__40.MoveNext()
0 17:25:01 CommandHandler | Command Executed after 0/0/0.036s
        User: Harsha1306#7180 [195323499856920576]
        Server: PRIVATE
        Channel: PRIVATE
        Message: .dcr 115
```

also see this error keep showing up on the console
```
0 17:27:28 GamesService | StackExchange.Redis.RedisConnectionException: UnableToResolvePhysicalConnection on GET
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2128                                                                                                        
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81                   
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1647                                                 
   at NadekoBot.Core.Services.Impl.RedisImagesCache.Get[T](String key) in /home/harsha1306/NadekoBot/NadekoBot.Core/Services/Impl/ImagesService.cs:line 232                                                                           
   at NadekoBot.Modules.Games.Services.GamesService.GetRandomCurrencyImage() in /home/harsha1306/NadekoBot/NadekoBot.Core/Modules/Games/Services/GamesService.cs:line 150                                                             
   at NadekoBot.Modules.Games.Services.GamesService.<>c__DisplayClass60_0.<<PotentialFlowerGeneration>b__0>d.MoveNext() in /home/harsha1306/NadekoBot/NadekoBot.Core/Modules/Games/Services/GamesService.cs:line 193 
```

**Comment by shikhir-arora** [comment]
What OS? Either way, kill the bot / stop it entirely. Then find the redis service and stop that too. Restart it if need be on Windows (I’m not a windows user). 

On Linux after confirming the bot is stopped and offline, do the following:

`ps aux | grep redis` which will return a process for redis and a process ID. Run `kill -KILL <id>` to stop that process for Redis. It should start up again automatically. Restart Nadeko and try again. If you get an error for redis on restart, do `systemctl restart redis.service` but that shouldn’t be an issue.

See if you then have the issue again and will go from there.

**Comment by harsha1306** [comment]
I'm running it on ubuntu 16.04.3, I followed the steps you listed but they're having issues at discord with people connecting from SJC and I'm affected by that. My DMs aren't reaching the bot. I'll let you know once I can DM the bot again.

**Comment by harsha1306** [comment]
After restarting the bot the reaction no longer is present but I still get that error in the console.

**Comment by Kwoth** [comment]
Your bot can't send the embed/message to that channel. Check your discord permissions.
