### ISSUE TITLE
.xp error

### ISSUE THREAD

**Issue by nicolastd5** [Kwoth/NadekoBot#1942]
xp return error
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NadekoBot.Core.Services.Impl.RedisImagesCache.Get[T](String key) in C:\Users\Nico\NadekoBot\NadekoBot.Core\Services\Impl\ImagesService.cs:line 232
   at NadekoBot.Modules.Xp.Services.XpService.<>c__DisplayClass42_0.<<GenerateImageAsync>b__0>d.MoveNext() in C:\Users\Nico\NadekoBot\NadekoBot.Core\Modules\Xp\Services\XpService.cs:line 602
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Xp.Xp.<Experience>d__5.MoveNext() in C:\Users\Nico\NadekoBot\NadekoBot.Core\Modules\Xp\Xp.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_1.<<BuildCommand>g__ExecuteCallback1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternalAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternalAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternalAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteAsync>d__40.MoveNext()

**Comment by Macley-Kun** [comment]
Public or selfhost?

**Comment by shivaco** [comment]
My guess is you don't have `xp.png` file in `Nadeko\system\data\images\xp` (Windows) or `NadekoBot/src/NadekoBot/bin/Release/netcoreapp2.0/data/images` (Linux)

**Comment by nicolastd5** [comment]
selfhost

xp.png is in the folder

**Comment by Kwoth** [comment]
Shivaco is right. You messed up your xp.png from the images/xp. Restart your bot.

If it doesn't work just reinstall the bot and copy over your old database an credentials.
