### ISSUE TITLE
.kick / .ban non-functional [Ubuntu 16.04 self-host]

### ISSUE THREAD

**Issue by FredericaBernkastel** [Kwoth/NadekoBot#1968]
- Unable to kick or ban members (`.kick`, `.ban`)
- Bot has `KickMembers` permission for sure
- Using latest v2.12.1 build
- Other commands are working fine

Stacktrace:
```
0 23:15:53 CommandHandler | Discord.Net.HttpException: The server responded with error 403: Forbidden
   at Discord.Net.Queue.RequestBucket.<SendAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Queue.RequestQueue.<SendAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendInternalAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<RemoveGuildMemberAsync>d__122.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.UserHelper.<KickAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Administration.Administration.UserPunishCommands.<Kick>d__21.MoveNext() in /home/bernkastel/.nadeko/NadekoBot/NadekoBot.Core/Modules/Administration/UserPunishCommands.cs:line 398
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternalAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternalAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternalAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteAsync>d__40.MoveNext()
0 23:15:53 CommandHandler | Command Executed after 0.008/0.02/1.312s
	User: Frederica Bernkastel#3247 [250211124065075201]
	Server: ★ Bern's tea party ★ [336141608464547843]
	Channel: control-center [397023748970250240]
	Message: .kick <@351577660494970890> test
```

**Comment by Macley-Kun** [comment]
0 23:15:53 CommandHandler | Discord.Net.HttpException: The server responded with error 403: Forbidden
   at Discord.Net.Queue.RequestBucket.<SendAsync>d__18.MoveNext()

You don't have access to Discord.Net.HttpException it seems... Would say it has to do with ratelimits maybe?

Is the issue repeat itself after a day or so?

**Comment by FredericaBernkastel** [comment]
Just installed it a hour ago;
Tried to make new application, but didn't help.

**Comment by shikhir-arora** [comment]
The channel that you’re typing the command in, does the bot have permissions there? Make sure the channel permissions don’t override.

**Comment by shikhir-arora** [comment]
Though that shouldn’t be an issue for this

**Comment by FredericaBernkastel** [comment]
You're right, sorry for taking your time :3
There was an implicit permission override i din't notice.
and error message deceived me...

**Comment by Macley-Kun** [comment]
Ey good to hear ya got it solved before new year :D
You can close this issue now 030 happy new year peeps 0/

Verstuurd vanaf mijn iPhone
