### ISSUE TITLE
When I Try to run updater this happened...

### ISSUE THREAD

**Issue by BunniRabbit** [Kwoth/NadekoBot#2034]
I was downloading the updater and installed the three things then restarted but when I run the app now it does tries to reinstall the program and sends this error I also cannot find it in add or remove programs or in my files ;~;

PLATFORM VERSION INFO
	Windows 			: 10.0.16299.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2556.0 built by: NET471REL1
	clr.dll 			: 4.7.2600.0 built by: NET471REL1LAST
	dfdll.dll 			: 4.7.2556.0 built by: NET471REL1
	dfshim.dll 			: 10.0.16299.15 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/Cathy/Desktop/NadekoBot%20Updater.appref-ms%7C
						Server		: cloudflare
	Deployment Provider url		: https://dl.nadekobot.me/NadekoUpdater.application
	Application url			: https://dl.nadekobot.me/Application%20Files/NadekoUpdater_1_0_0_20/NadekoUpdater.exe.manifest
						Server		: cloudflare

IDENTITIES
	Application Identity		: NadekoUpdater.exe, Version=1.0.0.20, Culture=neutral, PublicKeyToken=3315eafb86e6946f, processorArchitecture=msil, type=win32

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\Cathy\Desktop\NadekoBot Updater.appref-ms| resulted in exception. Following failure messages were detected:
		+ Exception occurred during store operation.
		+ Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	* Transaction at [1/25/2018 5:08:23 PM]
		- Staging of a component file (NadekoUpdater.exe) did not succeed.
		- Staging of a component (Octokit.dll.genman) did not succeed.
		- Staging of a component file (Octokit.dll) did not succeed.
		- Installation of deployment (https://dl.nadekobot.me/NadekoUpdater.application#NadekoUpdater.application, Version=1.0.0.20, Culture=neutral, PublicKeyToken=3315eafb86e6946f, processorArchitecture=msil) did not succeed.
		- Setting one or more of the deployment metadata did not succeed.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [1/25/2018 5:08:18 PM] : Activation of C:\Users\Cathy\Desktop\NadekoBot Updater.appref-ms| has started.
	* [1/25/2018 5:08:19 PM] : Installation of the application has started.
	* [1/25/2018 5:08:19 PM] : Processing of application manifest has successfully completed.
	* [1/25/2018 5:08:20 PM] : Found compatible runtime version 4.0.30319.
	* [1/25/2018 5:08:20 PM] : Request of trust and detection of platform is complete.
	* [1/25/2018 5:08:23 PM] : Downloading of subscription dependencies is complete.
	* [1/25/2018 5:08:23 PM] : Commit of the downloaded application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [1/25/2018 5:08:23 PM] System.Deployment.Application.DeploymentException (ComponentStore)
		- Exception occurred during store operation.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentStore.SubmitStoreTransaction(StoreTransactionContext storeTxn, SubscriptionState subState)
			at System.Deployment.Application.ComponentStore.SubmitStoreTransactionCheckQuota(StoreTransactionContext storeTxn, SubscriptionState subState)
			at System.Deployment.Application.ComponentStore.CommitApplication(SubscriptionState subState, CommitApplicationParams commitParams)
			at System.Deployment.Application.SubscriptionStore.CommitApplication(SubscriptionState& subState, CommitApplicationParams commitParams)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.UnauthorizedAccessException
		- Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Internal.Isolation.IStore.Transact(IntPtr cOperation, StoreTransactionOperation[] rgOperations, UInt32[] rgDispositions, Int32[] rgResults)
			at System.Deployment.Internal.Isolation.Store.Transact(StoreTransactionOperation[] operations, UInt32[] rgDispositions, Int32[] rgResults)
			at System.Deployment.Application.ComponentStore.SubmitStoreTransaction(StoreTransactionContext storeTxn, SubscriptionState subState)

COMPONENT STORE TRANSACTION DETAILS
	* Transaction at [1/25/2018 5:08:23 PM]
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: 548GEDTC.B6B.application
		+ System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
			- Status: Set
			- HRESULT: 0x0
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: NadekoUpdater.exe.manifest
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: Assets\nadeko_icon.ico
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: NadekoUpdater.exe.config
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: NadekoUpdater.exe.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x80070005
			- File: NadekoUpdater.exe
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Octokit.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Octokit.dll
		+ System.Deployment.Internal.Isolation.StoreOperationInstallDeployment
			- Status: Failed
			- HRESULT: 0x1
			- AppId: https://dl.nadekobot.me/NadekoUpdater.application#NadekoUpdater.application, Version=1.0.0.20, Culture=neutral, PublicKeyToken=3315eafb86e6946f, processorArchitecture=msil
		+ System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
			- Status: Failed
			- HRESULT: 0x1
		+ System.Deployment.Internal.Isolation.StoreTransactionOperationType (27)
			- HRESULT: 0x1

**Comment by Kwoth** [comment]
Disable antivirus, run it as administrator.

**Comment by Macley-Kun** [comment]
@BunniRabbit you tried what Kwoth recommanded you to do? Did it solve your issue?

**Comment by Macley-Kun** [comment]
Can we close the issue? Think the user changed his/her mind.
