### ISSUE TITLE
follow-up #2068 ~ redis

### ISSUE THREAD

**Issue by AnimeCat** [Kwoth/NadekoBot#2098]
@tukimoop told me to install redis on the updater, but I couldn't install the updater (will get screenshot). how do I install it manually?

also if you're wondering I had to post a follow-up because my issue was closed.

**Comment by tukimoop** [comment]
I'm gonna ask this since you haven't specified before. Are you using windows 64 bit?

if you are, follow this link: https://github.com/MicrosoftArchive/redis/releases

if not, tell me which OS and architecture.

**Comment by AnimeCat** [comment]
@tukimoop yes, thank you. I will comment if I need any more help.

**Comment by AnimeCat** [comment]
@tukimoop Another error. 

```
Unhandled Exception: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 890
   at NadekoBot.Core.Services.ShardsCoordinator..ctor()
   at NadekoBot.Program.Main(String[] args)
   at NadekoBot.Program.<Main>(String[] args)
```

**Comment by tukimoop** [comment]
Can you check if Redis is running in Windows Services?

**Comment by Macley-Kun** [comment]
And state your OS and if you use 64-bit.

**Comment by samdivaio** [comment]
`WinKey + X` select `Command Prompt (Admin)`
Paste this: 
`cd C:\Program Files\Redis` _(or `cd <redis other installed path>; if redis is in SystemPATH, skip this step)_
then
`redis-server`
it should start redis.

**Comment by AnimeCat** [comment]
@samdivaio redis server started, but then i get this:

```
-1 15:39:34 ShardsCoordinator | Starting NadekoBot v2.15.1
-1 15:39:36 ShardsCoordinator | StackExchange.Redis.RedisTimeoutException: Timeout performing SET NDEyNzQyNT_localimg_heads, inst: 2, queue: 4, qu: 0, qs: 4, qc: 0, wr: 0, wq: 0, in: 12, ar: 0, clientName: EC2AMAZ-E1JQ6JE, serverEndpoint: 127.0.0.1:6379, keyHashSlot: 10606 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2120
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
   at NadekoBot.Core.Services.Impl.RedisImagesCache.Set(String key, Object obj)
   at NadekoBot.Core.Services.Impl.RedisImagesCache.<<Reload>b__50_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Core.Services.Impl.RedisImagesCache.<Reload>d__50.MoveNext()

Unhandled Exception: StackExchange.Redis.RedisTimeoutException: Timeout performing SET NDEyNzQyNT_localimg_heads, inst: 2, queue: 4, qu: 0, qs: 4, qc: 0, wr: 0, wq: 0, in: 12, ar: 0, clientName: EC2AMAZ-E1JQ6JE, serverEndpoint: 127.0.0.1:6379, keyHashSlot: 10606 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2120
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
   at NadekoBot.Core.Services.Impl.RedisImagesCache.Set(String key, Object obj)
   at NadekoBot.Core.Services.Impl.RedisImagesCache.<<Reload>b__50_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Core.Services.Impl.RedisImagesCache.<Reload>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Core.Services.ShardsCoordinator..ctor()
   at NadekoBot.Program.Main(String[] args)
   at NadekoBot.Program.<Main>(String[] args)
```
