### ISSUE TITLE
followup #2098 ~ redis

### ISSUE THREAD

**Issue by AnimeCat** [Kwoth/NadekoBot#2102]
@samdivaio redis server started, but then i get this:

```
-1 15:39:34 ShardsCoordinator | Starting NadekoBot v2.15.1
-1 15:39:36 ShardsCoordinator | StackExchange.Redis.RedisTimeoutException: Timeout performing SET NDEyNzQyNT_localimg_heads, inst: 2, queue: 4, qu: 0, qs: 4, qc: 0, wr: 0, wq: 0, in: 12, ar: 0, clientName: EC2AMAZ-E1JQ6JE, serverEndpoint: 127.0.0.1:6379, keyHashSlot: 10606 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2120
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
   at NadekoBot.Core.Services.Impl.RedisImagesCache.Set(String key, Object obj)
   at NadekoBot.Core.Services.Impl.RedisImagesCache.<<Reload>b__50_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Core.Services.Impl.RedisImagesCache.<Reload>d__50.MoveNext()

Unhandled Exception: StackExchange.Redis.RedisTimeoutException: Timeout performing SET NDEyNzQyNT_localimg_heads, inst: 2, queue: 4, qu: 0, qs: 4, qc: 0, wr: 0, wq: 0, in: 12, ar: 0, clientName: EC2AMAZ-E1JQ6JE, serverEndpoint: 127.0.0.1:6379, keyHashSlot: 10606 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2120
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
   at NadekoBot.Core.Services.Impl.RedisImagesCache.Set(String key, Object obj)
   at NadekoBot.Core.Services.Impl.RedisImagesCache.<<Reload>b__50_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Core.Services.Impl.RedisImagesCache.<Reload>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Core.Services.ShardsCoordinator..ctor()
   at NadekoBot.Program.Main(String[] args)
   at NadekoBot.Program.<Main>(String[] args)
```

**Comment by Macley-Kun** [comment]
You've never told us what OS your using. Are you using a 64-bit build AND windows 8.1 or higher? Or maybe a linux distro?

Might help us with this.

**Comment by AnimeCat** [comment]
@Macley-Kun Yes, 64bit Windows 10 I believe.

**Comment by Macley-Kun** [comment]
Can you double check that? The part saying i believe worries me a little bit.

Also have you looked at the log yourself? They gave you this link: http://stackexchange.github.io/StackExchange.Redis/Timeouts

**Comment by AnimeCat** [comment]
@Macley-Kun Nothing on that page seemed to apply.

**Comment by Macley-Kun** [comment]
Mhm, you tried restarting and then starting Nadeko?

**Comment by AnimeCat** [comment]
@Macley-Kun Yes.

**Comment by sleeplesshero** [comment]
hello apparently im having the same problem with 64bit windows10, redis is installed and running but got this instead, any solution?
 [https://cdn.discordapp.com/attachments/412920804561387520/414695570427478018/unknown.png](url)

**Comment by sleeplesshero** [comment]
hello apparently im having the same issues with 64bit windows10, redis is installed and running until nadekobot stopped working, also the log shows exactly the same thing as the one in this thread. any solutions?

**Comment by Kwoth** [comment]
1. Try restarting your PC
2. Try restarting redis service
3. Navigate to the redis installation path, open CMD and then execute redis-cli.exe, press enter. Type `FLUSHALL`

**Comment by Macley-Kun** [comment]
@AnimeCat hows redis doing on your system? Did kwoth's steps helped you or your still dealing with it?

**Comment by xnaas** [comment]
Just as a note for potential future people reading this...I had an issue when I installed Redis and did **NOT** use the default port. I had to reinstall Redis with the default port for Nadeko to work.
