### ISSUE TITLE
StreamNotificationService Exception

### ISSUE THREAD

**Issue by ronelm2000** [Kwoth/NadekoBot#2123]
I keep on getting this error at seemingly random times when I play a song. I don't know why but there are consistent pauses when the music plays and this Exception appears, even on AWS.

OS:  Ubuntu 16.04.3 LTS
Run Method: `pm2`

```txt
0|Nadeko   | 0 19:45:54 StreamNotificationService | StackExchange.Redis.RedisTimeoutException: Timeout performing SCAN, inst: 1, queue: 1, qu: 0, qs: 1, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: , serverEndpoint: 127.0.0.1:6379 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
0|Nadeko   |    at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2101
0|Nadeko   |    at StackExchange.Redis.RedisServer.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisServer.cs:line 571
0|Nadeko   |    at StackExchange.Redis.RedisBase.CursorEnumerable`1.CursorEnumerator.MoveNext() in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 276
0|Nadeko   |    at NadekoBot.Core.Services.Impl.RedisCache.<GetAllStreamDataAsync>d__27.MoveNext() in /home/earth/NadekoBot/NadekoBot.Core/Services/Impl/RedisCache.cs:line 166
0|Nadeko   | --- End of stack trace from previous location where exception was thrown ---
0|Nadeko   |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
0|Nadeko   |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
0|Nadeko   |    at NadekoBot.Modules.Searches.Services.StreamNotificationService.<<-ctor>b__8_5>d.MoveNext() in /home/earth/NadekoBot/NadekoBot.Core/Modules/Searches/Services/StreamNotificationService.cs:line 65
0|Nadeko   | 0 19:47:27 StreamNotificationService | StackExchange.Redis.RedisTimeoutException: Timeout performing SCAN, inst: 1, queue: 1, qu: 0, qs: 1, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: , serverEndpoint: 127.0.0.1:6379 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
0|Nadeko   |    at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2101
0|Nadeko   |    at StackExchange.Redis.RedisServer.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisServer.cs:line 571
0|Nadeko   |    at StackExchange.Redis.RedisBase.CursorEnumerable`1.CursorEnumerator.MoveNext() in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 276
0|Nadeko   |    at NadekoBot.Core.Services.Impl.RedisCache.<GetAllStreamDataAsync>d__27.MoveNext() in /home/earth/NadekoBot/NadekoBot.Core/Services/Impl/RedisCache.cs:line 166
0|Nadeko   | --- End of stack trace from previous location where exception was thrown ---
0|Nadeko   |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
0|Nadeko   |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
0|Nadeko   |    at NadekoBot.Modules.Searches.Services.StreamNotificationService.<<-ctor>b__8_5>d.MoveNext() in /home/earth/NadekoBot/NadekoBot.Core/Modules/Searches/Services/StreamNotificationService.cs:line 65
```

**Comment by shikhir-arora** [comment]
Are you running the latest Nadeko? That error isn't related to music streaming, so it likely is a side effect of the server memory/CPU usage when streaming is stressing the server. Kwoth pushed a specific fix for this (potentially) a few days ago, and I haven't had any errors since, but my server has a lot of extra resources. The specific line that the error is thrown is a call to get the status of stream notifications from Redis cache.

**Comment by ronelm2000** [comment]
Someone else was using `top` to examine the resources used but it never really went beyond 20% on average on both memory and CPU so I'm really wondering why would the server be stressed at that point.

[Case in point.](https://media.discordapp.net/attachments/299029722757726208/416128556175851531/unknown.png)

I also recently let the server auto-update and the problems still persist. So 🤷‍♂️

**Comment by shikhir-arora** [comment]
While you experience the problems or play music, if you can run this:

`sudo redis-cli --intrinsic-latency 150`

And post the output.

**Comment by ronelm2000** [comment]
```sh
earth@kagari:~$ sudo redis-cli --intrinsic-latency 150
Max latency so far: 1 microseconds.
Max latency so far: 25 microseconds.
Max latency so far: 40 microseconds.
Max latency so far: 42 microseconds.
Max latency so far: 1310 microseconds.
Max latency so far: 1892 microseconds.
Max latency so far: 4320 microseconds.
Max latency so far: 5949 microseconds.
Max latency so far: 7049 microseconds.
Max latency so far: 8272 microseconds.
Max latency so far: 8776 microseconds.
Max latency so far: 9578 microseconds.

239766249 total runs (avg latency: 0.6256 microseconds / 6256.09 nanoseconds per run).
Worst run took 15310x longer than the average latency.
earth@kagari:~$ sudo redis-cli --intrinsic-latency 150
Max latency so far: 1 microseconds.
Max latency so far: 18 microseconds.
Max latency so far: 21 microseconds.
Max latency so far: 24 microseconds.
Max latency so far: 72 microseconds.
Max latency so far: 1536 microseconds.
Max latency so far: 2475 microseconds.
Max latency so far: 5451 microseconds.
Max latency so far: 6587 microseconds.
Max latency so far: 10282 microseconds.

244468012 total runs (avg latency: 0.6136 microseconds / 6135.77 nanoseconds per run).
Worst run took 16757x longer than the average latency.
```

**Comment by shikhir-arora** [comment]
I ran it on a few servers, the first one is the one I use for Nadeko (among other things). Does it happen only when you play music?

```hs

vlexar@node1:~/main/vlexar$ sudo redis-cli --intrinsic-latency 150
Max latency so far: 1 microseconds.
Max latency so far: 20 microseconds.
Max latency so far: 23 microseconds.
Max latency so far: 24 microseconds.
Max latency so far: 28 microseconds.
Max latency so far: 38 microseconds.
Max latency so far: 40 microseconds.
Max latency so far: 46 microseconds.

4445529895 total runs (avg latency: 0.0337 microseconds / 33.74 nanoseconds per run).
Worst run took 1363x longer than the average latency.
```

```hs

vlexar@frontend-dev-perf1:~$ sudo redis-cli --intrinsic-latency 150
Max latency so far: 1 microseconds.
Max latency so far: 23 microseconds.
Max latency so far: 110 microseconds.
Max latency so far: 459 microseconds.
Max latency so far: 3847 microseconds.

2563338951 total runs (avg latency: 0.0585 microseconds / 58.52 nanoseconds per run).
Worst run took 65741x longer than the average latency.
```

**Comment by ronelm2000** [comment]
Hmm, it does seem to persist without music.
```sh
earth@kagari:~$ sudo redis-cli --intrinsic-latency 150
Max latency so far: 1 microseconds.
Max latency so far: 30 microseconds.
Max latency so far: 41 microseconds.
Max latency so far: 170 microseconds.
Max latency so far: 228 microseconds.
Max latency so far: 697 microseconds.
Max latency so far: 1034 microseconds.
Max latency so far: 1371 microseconds.
Max latency so far: 1665 microseconds.
Max latency so far: 1743 microseconds.
Max latency so far: 3674 microseconds.
Max latency so far: 8251 microseconds.
Max latency so far: 8395 microseconds.
Max latency so far: 8401 microseconds.
Max latency so far: 8572 microseconds.
Max latency so far: 11467 microseconds.

236749000 total runs (avg latency: 0.6336 microseconds / 6335.82 nanoseconds per run).
Worst run took 18099x longer than the average latency.
```

I guess time for Plan B. I'm switching to CentOS and see if that changes things.

**Comment by shikhir-arora** [comment]
It almost certainly isn't an OS issue. There could still be a race condition or lock in the code, the fix Kwoth pushed was a possible fix. On servers that are powerful, it won't be noticeable. But the OS is not going to really be the culprit here, on the same hardware. At least there shouldn't be any real difference between two Linux distributions when it comes to this.

**Comment by ronelm2000** [comment]
This is the redis run on AWS micro2 btw.

First run is without music, the 2nd is with music.

I also I haven't tried using tmux yet for either configuration.
```sh
ubuntu@ip-172-31-11-182:~$ sudo redis-cli --intrinsic-latency 150
Max latency so far: 1 microseconds.
Max latency so far: 3 microseconds.
Max latency so far: 12 microseconds.
Max latency so far: 100 microseconds.
Max latency so far: 155 microseconds.
Max latency so far: 258 microseconds.
Max latency so far: 280 microseconds.
Max latency so far: 3414 microseconds.
Max latency so far: 4488 microseconds.

775206468 total runs (avg latency: 0.1935 microseconds / 1934.97 nanoseconds per run).
Worst run took 23194x longer than the average latency.
ubuntu@ip-172-31-11-182:~$ sudo redis-cli --intrinsic-latency 150
Max latency so far: 1 microseconds.
Max latency so far: 11 microseconds.
Max latency so far: 12 microseconds.
Max latency so far: 13 microseconds.
Max latency so far: 1456 microseconds.
Max latency so far: 1457 microseconds.
Max latency so far: 1601 microseconds.
Max latency so far: 1648 microseconds.
Max latency so far: 3175 microseconds.
Max latency so far: 7067 microseconds.

720239875 total runs (avg latency: 0.2083 microseconds / 2082.64 nanoseconds per run).
Worst run took 33933x longer than the average latency.
```

**Comment by Kwoth** [comment]
Should be working fine by now. Made a few changes.

**Comment by TiBarification** [comment]
Bug persist on version 2.6.11
```
0 02:28:59 StreamNotificationService | StackExchange.Redis.RedisTimeoutException: Timeout performing SCAN, inst: 1, queue: 32, qu: 0, qs: 32, qc: 0, wr: 0, wq: 0, in: 466, ar: 0, clientName: , serverEndpoint: 127.0.0.1:6379 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2101
   at StackExchange.Redis.RedisServer.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisServer.cs:line 571
   at StackExchange.Redis.RedisBase.CursorEnumerable`1.CursorEnumerator.MoveNext() in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 295
   at NadekoBot.Core.Services.Impl.RedisCache.<GetAllStreamDataAsync>d__27.MoveNext() in /home/nadeko/NadekoBot/NadekoBot.Core/Services/Impl/RedisCache.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Searches.Services.StreamNotificationService.<<-ctor>b__8_5>d.MoveNext() in /home/nadeko/NadekoBot/NadekoBot.Core/Modules/Searches/Services/StreamNotificationService.cs:line 65
0 02:33:37 StreamNotificationService | StackExchange.Redis.RedisTimeoutException: Timeout performing SCAN, inst: 1, queue: 3, qu: 0, qs: 3, qc: 0, wr: 0, wq: 0, in: 14, ar: 0, clientName: , serverEndpoint: 127.0.0.1:6379 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2101
   at StackExchange.Redis.RedisServer.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisServer.cs:line 571
   at StackExchange.Redis.RedisBase.CursorEnumerable`1.CursorEnumerator.MoveNext() in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 276
   at NadekoBot.Core.Services.Impl.RedisCache.<GetAllStreamDataAsync>d__27.MoveNext() in /home/nadeko/NadekoBot/NadekoBot.Core/Services/Impl/RedisCache.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Searches.Services.StreamNotificationService.<<-ctor>b__8_5>d.MoveNext() in /home/nadeko/NadekoBot/NadekoBot.Core/Modules/Searches/Services/StreamNotificationService.cs:line 65
0 02:36:20 StreamNotificationService | StackExchange.Redis.RedisTimeoutException: Timeout performing SCAN, inst: 0, queue: 5, qu: 1, qs: 4, qc: 0, wr: 0, wq: 1, in: 7, ar: 0, clientName: , serverEndpoint: 127.0.0.1:6379 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2101
   at StackExchange.Redis.RedisServer.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisServer.cs:line 571
   at StackExchange.Redis.RedisBase.CursorEnumerable`1.CursorEnumerator.MoveNext() in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 295
   at NadekoBot.Core.Services.Impl.RedisCache.<GetAllStreamDataAsync>d__27.MoveNext() in /home/nadeko/NadekoBot/NadekoBot.Core/Services/Impl/RedisCache.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Searches.Services.StreamNotificationService.<<-ctor>b__8_5>d.MoveNext() in /home/nadeko/NadekoBot/NadekoBot.Core/Modules/Searches/Services/StreamNotificationService.cs:line 65
```

**Comment by ronelm2000** [comment]
@TiBarification by any chance are you using a VM as well? (AWS EC2, etc.)

**Comment by TiBarification** [comment]
No, just raw ubuntu 16.04

**Comment by TiBarification** [comment]
@Kwoth can you reopen that issue?

**Comment by TiBarification** [comment]
@Kwoth can you reopen this issue?
