### ISSUE TITLE
.fwdmsgs not working on latest and second to latest update (windows)

### ISSUE THREAD

**Issue by Coldvictory** [Kwoth/NadekoBot#2163]
No response in direct messages at all, tried toggling the function several times as well as re-installing it
Edit: also no error in console

**Comment by Coldvictory** [comment]
New error after latest update:

`0 23:37:42 CommandHandler | System.ArgumentException: Argument cannot be blank
Parameter name: Content
   at Discord.Preconditions.NotNullOrEmpty(String obj, String name, String msg)
   at Discord.API.DiscordRestApiClient.<CreateMessageAsync>d__77.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.ChannelHelper.<SendMessageAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.SocketDMChannel.<Discord-IMessageChannel-SendMessageAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Core.Services.CommandHandler.<TryRunCommand>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Core.Services.CommandHandler.<MessageReceivedHandler>d__52.MoveNext()`

**Comment by Kwoth** [comment]
Works fine.

**Comment by Coldvictory** [comment]
This happens whenever someone (me or anyone else) messages the bot with a non-command
