### ISSUE TITLE
I mean, its all I wanted... sorta

### ISSUE THREAD

**Issue by moldyburrito56** [Kwoth/NadekoBot#2216]
NSFW commands aren't working. Nadeko role created and applied. .sm nsfw enable / .cm nsfw #TheChannel tried. pls help.
`
-1 05:36:50 ShardsCoordinator | Starting NadekoBot v2.17.4
0 05:36:54 NadekoBot | Shard 0 logging in ...
0 05:36:55 NadekoBot | Shard 0 logged in.
0 05:36:55 NadekoBot | Shard 0 loading services...
0 05:36:56 NadekoStrings | Loaded 26 languages in 0.08s
0 05:36:57 NServiceProvider | All services loaded in 0.76s
0 05:36:57 NadekoBot | Shard 0 connected in 3.04s
0 05:36:57 NadekoBot | Shard 0 ready.
0 05:37:02 SelfService | Created 1 out of 1 owner message channels.
0 05:37:12 CommandHandler | Command Errored after 0/0.016/0.078s
        User: xxx#xxx [xxx]
        Server: aaa [xxx]
        Channel: general [xxx]
        Message: .butts
        Error: Command precondition group nsfw_or_dm failed.
0 05:37:16 StreamNotificationService | StackExchange.Redis.RedisCommandException: This operation is not available unless admin mode is enabled: KEYS
   at StackExchange.Redis.ConnectionMultiplexer.CheckMessage(Message message) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 477
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
   at StackExchange.Redis.RedisServer.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisServer.cs:line 571
   at StackExchange.Redis.RedisServer.Keys(Int32 database, RedisValue pattern, Int32 pageSize, Int64 cursor, Int32 pageOffset, CommandFlags flags) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisServer.cs:line 303
   at NadekoBot.Core.Services.Impl.RedisCache.<GetAllStreamDataAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Searches.Services.StreamNotificationService.<<-ctor>b__9_5>d.MoveNext()`

**Comment by shivaco** [comment]
Mark the channel as NSFW.

**Comment by Kwoth** [comment]
That's the solution psosibly ,and the error you're showing is possibly a permission issue on your pc. Make sure to install reids and run your bot as admin.
