### ISSUE TITLE
Self-hosted error

### ISSUE THREAD

**Issue by ForgottenGlory** [Kwoth/NadekoBot#2255]
I'm not certain what's causing this, but it's only just started happening today.

Unhandled Exception: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 876
   at NadekoBot.Core.Services.ShardsCoordinator..ctor()
   at NadekoBot.Program.Main(String[] args)
   at NadekoBot.Program.<Main>(String[] args)

**Comment by xnaas** [comment]
@ForgottenGlory is Redis installed? If so, when you installed it, did you leave the default port?

**Comment by FairPlay137** [comment]
Try reinstalling Redis.
