### ISSUE TITLE
MTG Command not giving any response

### ISSUE THREAD

**Issue by msfloopsy** [Kwoth/NadekoBot#2295]
Hey there!

Tried countless times to get the mtg/magicthegathering command to work on multiple servers, to no avail. support server said to come to github to report it, so here I am! On larger servers, nothing happens at all, however on a smaller server of mine, nadeko was typing for about 5 seconds after the command being entered, then nothing ended up being sent. Hopefully there's an easy solution, because that command would be really nice to have for our mtg group! Thanks in advance

**Comment by Gremagol** [comment]
This is what I get on my selfhost, seems to be down ?

`0 09:51:31 CommandHandler | System.Net.Http.HttpRequestException: Response status code does not indicate success: 503 (Service Unavailable).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.<GetStringAsyncCore>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Searches.Searches.<MagicTheGathering>d__30.MoveNext() in /root/Ene/NadekoBot/NadekoBot.Core/Modules/Searches/Searches.cs:line 498
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteInternalAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteInternalAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteInternalAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteAsync>d__44.MoveNext()
`

**Comment by Gremagol** [comment]
Seems like the it's down

![mtcerror](https://user-images.githubusercontent.com/24619854/39965121-a55b4de2-5693-11e8-9839-054538b1e91d.PNG)

**Comment by Kwoth** [comment]
Yea the deckbrew.com website seems to be down.
