### ISSUE TITLE
ERROR: the process #### not found crashes every few hours on Bot pc windows 10 x64 

### ISSUE THREAD

**Issue by TamaKaiNya** [Kwoth/NadekoBot#2302]
![image](https://user-images.githubusercontent.com/32908560/40074151-d9c4b3d4-5846-11e8-8edd-59ea8fb9de27.png)

I have been running my bot for 4 days with no issues but today it keeps crashing. Help!

**Comment by Macley-Kun** [comment]
What have you tried so far?

- Updated your windows fully?
- Re-moved nadeko completley? (backup credentias.json en the database!)
- Disable firewall?
- Disable anti-virus?
- Checked after a while again, maybe it was Discord?

**Comment by TamaKaiNya** [comment]
I have done all the steps above. Seems it was a fluke because it never crashed again after yesterday

**Comment by TamaKaiNya** [comment]
I spoke too soon, it crashed again.

**Comment by TamaKaiNya** [comment]
new update spits out 

Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'System.Threading.QueueUserWorkItemCallback' to type 'System.Net.Sockets.BaseOverlappedAsyncResult'.
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
ERROR: The process "2244" not found.

**Comment by Macley-Kun** [comment]
Mhm, i don't really get the process not found error.. @Kwoth any clue what the issue could be?

**Comment by xnaas** [comment]
Mine didn't start crashing until 2.22.0, but now it crashes once per day sometime between 1am and 7am.

![image](https://user-images.githubusercontent.com/8271327/40237453-1b42d846-5a76-11e8-8e9b-25ea916bf7ad.png)


```
-1 02:15:41 ShardsCoordinator | !!! SHARD 0 IS IN Disconnected STATE !!!
-1 02:15:46 ShardsCoordinator | Auto-restarting shard 0
-1 02:15:46 ShardsCoordinator | Shard 0 is scheduled for a restart because it's unresponsive.
-1 02:15:52 ShardsCoordinator | Auto-restarting shard 0
0 02:15:54 NadekoBot | Shard 0 logging in ...

Unhandled Exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The server name or address could not be resolved
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Rest.DefaultRestClient.<SendInternalAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Rest.DefaultRestClient.<SendAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Queue.RestRequest.<SendAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Queue.RequestBucket.<SendAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Queue.RequestQueue.<SendAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendInternalAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendAsync>d__57`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<GetVoiceRegionsAsync>d__144.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.DiscordSocketClient.<OnLoginAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<LoginAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Program.<Main>(String[] args)
ERROR: The process "30388" not found.
-1 02:17:16 ShardsCoordinator | Shard 0 is scheduled for a restart because it's unresponsive.
-1 02:17:22 ShardsCoordinator | Auto-restarting shard 0
0 02:17:24 NadekoBot | Shard 0 logging in ...
0 02:17:25 NadekoBot | Shard 0 logged in.
0 02:17:25 NadekoBot | Shard 0 loading services...
0 02:17:26 NadekoStrings | Loaded 26 languages in 0.15s
0 02:17:26 NServiceProvider | All services loaded in 0.65s
0 02:17:26 NadekoBot | Shard 0 connected in 2.25s
0 02:17:27 NadekoBot | Shard 0 ready.
```

Seems to be related to re-connecting to Discord.

**Comment by shivaco** [comment]
@xnaas Yes, your issue is most likely related to recent Discord outages.

**Comment by xnaas** [comment]
Sure, but the bot shouldn't just crash. There's been outages without crashes before. 😛

**Comment by TamaKaiNya** [comment]
Update: seems that the error occurs when playing music for long periods of time but it also can happen randomly at idle @Macley-Kun @Kwoth

**Comment by Macley-Kun** [comment]
I'm not to fine on nadeko's music module. Due to personal reasons. Therefore if someone has issues with it. I recommend them not using the Music module then.
Out of random seems a bit strange. Do logs not say more? Maybe something very specific happens?

**Comment by senprime** [comment]
I have to run redis and nadeko prompts to get my bot online. I hate Windows 10.

**Comment by Macley-Kun** [comment]
senprime: install Ubuntu I would say...

**Comment by TamaKaiNya** [comment]
@Macley-Kun no other messages pop up.

**Comment by TamaKaiNya** [comment]
anything I can do?

**Comment by senprime** [comment]
Reinstall Discord without Nadeko Kwoth is forcing his hacked update to the .exe codex and basically controls and see everything you do. I ran debug and got the error script saved and reported to ToS and C# developers in California I know.

**Comment by senprime** [comment]
You might want to start a Windows repair to because they are using Windows Linux, and Zerg is using Linux. They disconnected from their host and I cannot maintain new Bot host because I shut their fucking ass down

**Comment by Kwoth** [comment]
@xnaas  it's still crashing for you? I had this issue yesterday, when the PC i was running the bot on was too slow for the size of the bot.

**Comment by xnaas** [comment]
I haven't gotten any more crashes since stopping all Twitch notifications. This may or may not be related to #2212. I don't know. I just know that every issue I had with my self-hosted instance pretty much cleared up after killing all the DB entires related to twitch notifications.

Also, I doubt [my server](https://pcpartpicker.com/user/xnaas/saved/kQ86Mp) was too crippled by (at the time) 2 servers and <50 users. 😜

**Comment by Macley-Kun** [comment]
Any updates or time to close?

**Comment by TamaKaiNya** [comment]
hmm no crashes so far

**Comment by Macley-Kun** [comment]
Keep an eye out until sunday. If nothing happens we can assume your issue is resolved.
