### ISSUE TITLE
StreamNotificationService errors

### ISSUE THREAD

**Issue by RedFoxNightfox** [Kwoth/NadekoBot#2318]
I get well over 100 error messages a day on my selfhost, both on my local PC, and on my VPS with this exact same error message, save for the timestamps:

```
0 21:40:08 StreamNotificationService | System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The server returned an invalid or unrecognized response
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Searches.Services.StreamNotificationService.<GetStreamStatus>d__13.MoveNext()
```

Many times I will generate 4 to 9 of these with the same exact timestamp. In a few instances, these errors have seemingly caused the bot to stop responding to commands.

Sometimes causes bot to no longer be able to autodelete completed commands when set to do so when producing 60+ errors a minute. restart required to return to normal operation

**Comment by MaybeGoogle** [comment]
Comment: slightly different from #2212 because the bot crashes.

**Comment by Kwoth** [comment]
Yea just move this to #2212 and give us more details on how many streams you have etc.
