### ISSUE TITLE
Probably just a dumb mistake

### ISSUE THREAD

**Issue by Apollo1127** [Kwoth/NadekoBot#2328]
I'm using the docker and cant seem to get this to work. I've made sure my token is correct. I seem to be missing the folder for the credentials.json I'm really lost, thanks.

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Ryty>docker stop nadeko
nadeko

C:\Users\Ryty>docker start -a nadeko
Dotnet installed.

Linking Nadeko Credentials
bash: ./patch.sh: No such file or directory

Patching Nadeko Data Folder

Starting Redis-Server

Running NadekoBot with auto restart Please wait.
Using launch settings from /opt/NadekoBot/src/NadekoBot/Properties/launchSetting
s.json...
-1 06:20:41 ShardsCoordinator | Starting NadekoBot v2.22.0
Using launch settings from /opt/NadekoBot/src/NadekoBot/Properties/launchSetting
s.json...
0 06:21:06 NadekoBot | Shard 0 logging in ...

Unhandled Exception: Discord.Net.HttpException: The server responded with error
401: 401: Unauthorized
   at Discord.Net.Queue.RequestBucket.<SendAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.Net.Queue.RequestQueue.<SendAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.API.DiscordRestApiClient.<SendInternalAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.API.DiscordRestApiClient.<SendAsync>d__57`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.API.DiscordRestApiClient.<GetVoiceRegionsAsync>d__144.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.WebSocket.DiscordSocketClient.<OnLoginAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NadekoBot.NadekoBot.<LoginAsync>d__47.MoveNext() in /opt/NadekoBot/NadekoB
ot.Core/Services/NadekoBot.cs:line 238
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NadekoBot.NadekoBot.<RunAsync>d__50.MoveNext() in /opt/NadekoBot/NadekoBot
.Core/Services/NadekoBot.cs:line 275
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__52.MoveNext() in /opt/NadekoBot/N
adekoBot.Core/Services/NadekoBot.cs:line 331
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NadekoBot.Program.<Main>(String[] args)

**Comment by senprime** [comment]
I don't think you people realize that you are getting shut down. I've spoken at the windows and Discord and they do not approve so good luck keep trying actually I hope you fail

**Comment by xnaas** [comment]
@Apollo1127 ignore them, they're just some bored retard.

**Comment by ez314** [comment]
@Apollo1127 make sure your token is right. One easy mistake is accidentally using the client secret. If you are sure the token is right, try generating a new bot token. 

After you edit `credentials.json`, run
`docker cp credentials.json nadeko:/root/nadeko`
`docker start -a nadeko`

**Comment by Apollo1127** [comment]
Thank you that command worked for me!
