### ISSUE TITLE
Bot crashes when trying to play songs

### ISSUE THREAD

**Issue by Mizunami2025** [Kwoth/NadekoBot#2362]
Bot crashes when i use any command to play songs.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at NadekoBot.Modules.Music.Common.SongBuffer.Dispose()
   at NadekoBot.Modules.Music.Common.MusicPlayer.<PlayerLoop>d__106.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by Macley-Kun** [comment]
@Mizunami2025 you did what Kwoth asked you to do?

If it helped, don't forget to close the issue!!
