### ISSUE TITLE
The use of the .xp command when the bot starting throwing an error.

### ISSUE THREAD

**Issue by RikoDEV** [Kwoth/NadekoBot#2377]
1. Run selfhosted bot.
2. Use .xp command in server in 6-10 sec after bot start.

```
0 11:46:06 CommandHandler | System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source)
   at NadekoBot.Core.Services.Database.Repositories.Impl.DiscordUserRepository.<GetUserGlobalRankingAsync>d__3.MoveNext() in /home/nadeko/NadekoBot/NadekoBot.Core/Services/Database/Repositories/Impl/DiscordUserRepository.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Xp.Services.XpService.<GetUserStatsAsync>d__36.MoveNext() in /home/nadeko/NadekoBot/NadekoBot.Core/Modules/Xp/Services/XpService.cs:line 471
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Xp.Services.XpService.<GenerateImageAsync>d__41.MoveNext() in /home/nadeko/NadekoBot/NadekoBot.Core/Modules/Xp/Services/XpService.cs:line 601
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Xp.Xp.<Experience>d__5.MoveNext() in /home/nadeko/NadekoBot/NadekoBot.Core/Modules/Xp/Xp.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteInternalAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteInternalAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteInternalAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteAsync>d__44.MoveNext()
```

**Comment by Kaoticz** [comment]
Do you also happen to have trouble running the `.slot` command?
Are you using **dotNET 2.1.3**?

**Comment by RikoDEV** [comment]
@Kaoticz 

1. No, `.slot` command working fine.
2. No, `.NET Command Line Tools (2.0.0)`, `dotnet-host (2.0.6-1)`
