### ISSUE TITLE
The .convert command does not work and causes an error in the console.

### ISSUE THREAD

**Issue by RikoDEV** [Kwoth/NadekoBot#2382]
| Version: | v2.23.0     |
|----------|-------------|
| Type:    | self-hosted |
| Server:  | Debian      |

When trying to use the command (.convert m km 1000), nothing happens and an error occurs in the console.

Log:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NadekoBot.Modules.Utility.Services.ConverterService.get_Units() in /home/nadeko/NadekoBot/NadekoBot.Core/Modules/Utility/Services/ConverterService.cs:line 20
   at NadekoBot.Modules.Utility.Utility.UnitConverterCommands.<Convert>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteInternalAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteInternalAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Commands.CommandInfo.<ExecuteInternalAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteAsync>d__44.MoveNext()
------
```

**Comment by nixyspl** [comment]
Same with the .convertlist command.

**Comment by xnaas** [comment]
Working on a Windows host of the bot. So it's either something wrong with your install or Debian/Linux specific. Would be helpful if someone else on Linux could try... :D

<img width="629" alt="image" src="https://user-images.githubusercontent.com/8271327/42094282-e48e9b3a-7b74-11e8-902d-a3ac2e5d4246.png">

**Comment by xnaas** [comment]
@RikoDEV would you be able to backup your database and data folders and retry a bot install?

**Comment by Kaoticz** [comment]
Does the `.convert` command requires any API in particular?
Mine is working fine. **Ubuntu 16.04.4 LTS**
![miles](https://user-images.githubusercontent.com/1812311/42116350-3e026356-7bcd-11e8-8af4-f2e294438bd8.png)

**Comment by Kwoth** [comment]
http://api.fixer.io/latest yes it has been deprecated, which means if you don't have the data already stored in your local redis cache, it won't work. (new users) I will try hosting the api myself like i did with many others so far to prevent limitations.
