### ISSUE TITLE
Unhandled Exception: System.XmlException

### ISSUE THREAD

**Issue by SgtPineapple1st** [Kwoth/NadekoBot#239]
I closed my hosted Nadeko last night, and opened it up this morning... it threw an error and crashed. I had an issue yesterday with an error that I fixed by reinstalling the bot. After trying that this morning, Nadeko started throwing a different error.
`Unhandled Exception: System.Xml.XmlException: An error occurred while parsing EntityName. Line 5, position 363.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseEntityName()
   at System.Xml.XmlTextReaderImpl.ParseEntityReference()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(Stream inStream)
   at ScaredFingers.UnitsConversion.WebExchangeRatesProvider.BuildDataSet(String url) in W:\tmp\ScaredFingers.UnitsConversion\CurrencyConversion.cs:line 294
   at ScaredFingers.UnitsConversion.WebExchangeRatesProvider..ctor(String fileUrl, Stream XSLTFile) in W:\tmp\ScaredFingers.UnitsConversion\CurrencyConversion.cs:line 279
   at ScaredFingers.UnitsConversion.WebExchangeRatesProvider..ctor() in W:\tmp\ScaredFingers.UnitsConversion\CurrencyConversion.cs:line 260
   at NadekoBot.Modules.Searches.Commands.ConverterCommand.reInitCurrencyConverterTable() in C:\Users\Master\Documents\Visual Studio 2015\Projects\NadekoBot\NadekoBot\Modules\Searches\Commands\ConverterCommand.cs:line 112
   at NadekoBot.Modules.Searches.Commands.ConverterCommand..ctor(DiscordModule module) in C:\Users\Master\Documents\Visual Studio 2015\Projects\NadekoBot\NadekoBot\Modules\Searches\Commands\ConverterCommand.cs:line 26
   at NadekoBot.Modules.Searches.SearchesModule..ctor() in C:\Users\Master\Documents\Visual Studio 2015\Projects\NadekoBot\NadekoBot\Modules\Searches\SearchesModule.cs:line 27
   at NadekoBot.NadekoBot.Main() in C:\Users\Master\Documents\Visual Studio 2015\Projects\NadekoBot\NadekoBot\NadekoBot.cs:line 181`

**Comment by Kwoth** [comment]
@tg44 might have info on this? It wasn't me who implemented currency conversion

**Comment by tg44** [comment]
Tell me sth about your context, Win machine, behind or not behind a proxy, you build the bot from source or grab the exe from updater or releases tab? This exception nearly say nothing at all :)

**Comment by SgtPineapple1st** [comment]
Windows 10... no proxy... it's the bot from the updater... It was working fine yesterday, but stopped when I tried starting it today.

**Comment by tg44** [comment]
I think I fixed this or at least it will not crash the bot.

**Comment by Kwoth** [comment]
Should be fixed in the **upcoming** release. Reopen the issue if it isn't

**Comment by Tsumiki-Chan** [comment]
This problem still seems to exist
