### ISSUE TITLE
NadekoBot Closes With Error After Opening (Closed)

### ISSUE THREAD

**Issue by Redeyes260** [Kwoth/NadekoBot#2416]
I've changed nothing with NadekoBot as it worked fine until a couple days ago. This is the error I receive when trying to start NadekoBot. After sustaining for a few seconds, the program closes out. I don't know much code, so I've know clue what this means.

-1 18:50:32 ShardsCoordinator | Starting NadekoBot v2.24.5

Unhandled Exception: StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 876
   at NadekoBot.Core.Services.ShardsCoordinator..ctor()
   at NadekoBot.Program.Main(String[] args)
   at NadekoBot.Program.<Main>(String[] args)

**Comment by xnaas** [comment]
Did you install Redis?

**Comment by Redeyes260** [comment]
Fixed the issue. Thank you.

**Comment by xnaas** [comment]
Glad that did the trick! 😄
