### ISSUE TITLE
images.json no longer recognizes images on network paths

### ISSUE THREAD

**Issue by xnaas** [Kwoth/NadekoBot#2529]
If I try to do an `.imagesreload`, the console gets this:

```
0 10:05:15 ImageLoader | System.IO.DirectoryNotFoundException: Could not find a part of the path 'M:\p.xnaas.info\as\coins\dogecoin.png'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.ReadAllBytesAsync(String path, CancellationToken cancellationToken)
   at NadekoBot.Core.Services.Common.ImageLoader.GetImageData(Uri uri)
0 10:05:15 ImageLoader | System.IO.DirectoryNotFoundException: Could not find a part of the path 'M:\p.xnaas.info\as\coins\bitcoin.png'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.ReadAllBytesAsync(String path, CancellationToken cancellationToken)
   at NadekoBot.Core.Services.Common.ImageLoader.GetImageData(Uri uri)
0 10:05:15 ImageLoader | 0/1 URIs for the key 'Coins_Heads' have been loaded. Some of the supplied URIs are either unavailable or invalid.
0 10:05:15 ImageLoader | System.IO.DirectoryNotFoundException: Could not find a part of the path 'M:\p.xnaas.info\as\currency\trump-20.jpg'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.ReadAllBytesAsync(String path, CancellationToken cancellationToken)
   at NadekoBot.Core.Services.Common.ImageLoader.GetImageData(Uri uri)
0 10:05:15 ImageLoader | 0/1 URIs for the key 'Coins_Tails' have been loaded. Some of the supplied URIs are either unavailable or invalid.
0 10:05:15 ImageLoader | System.IO.DirectoryNotFoundException: Could not find a part of the path 'M:\p.xnaas.info\as\currency\vn-20.jpg'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.ReadAllBytesAsync(String path, CancellationToken cancellationToken)
   at NadekoBot.Core.Services.Common.ImageLoader.GetImageData(Uri uri)
0 10:05:15 ImageLoader | 0/2 URIs for the key 'Currency' have been loaded. Some of the supplied URIs are either unavailable or invalid.
0 10:05:16 CommandHandler | Command Executed after 0.000/0.110s
        User: xnaas#4357 [83983966608068608]
        Server: Action Sack [141249302260350977]
        Channel: spam [226086096675667969]
        Message: .imagesreload
0 10:05:18 RedisImagesCache | Images reloaded in 2.07s
```

The formatting is standard and unchanged for weeks. This issue started up a few updates ago, but I don't remember when. We only noticed because `.bf` stopped showing results as it couldn't load the images. Also `.flip` doesn't work, etc. And yes, very obviously the files are more than easily accessible from the server. The issues is the bot, not anything else. 😉 

Not sure if it's related, but I can't do `.plant` (`.plant 1`) either. It says I don't have enough currency even though I have 63000.

**Comment by xnaas** [comment]
Might as well add a screenshot of the images.json section that's been fully functional until recently.

<img width="441" alt="image" src="https://user-images.githubusercontent.com/8271327/44534238-eae8fc00-a6bc-11e8-9eb2-d93851729ada.png">

**Comment by Kwoth** [comment]
I can't test so we'd have to figure something out to let me remote into your PC and see what's up.

**Comment by xnaas** [comment]
Meh, it's not a big enough issue to dig into.
