### ISSUE TITLE
NadekoBot not starting 

### ISSUE THREAD

**Issue by tanelq** [Kwoth/NadekoBot#2540]
So bot seems to start but fails for some reason. :(

Help please!

NadekoBot 1.9+
Mirai was here.
youtube-dl is up-to-date (2018.08.28)
Dotnet installed.
  Restore completed in 41.71 ms for /home/nadeko/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj.
  Restore completed in 2.63 ms for /home/nadeko/NadekoBot/NadekoBot.Tests/NadekoBot.Tests.csproj.
  Restore completed in 1.89 ms for /home/nadeko/NadekoBot/src/NadekoBot/NadekoBot.csproj.
Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 41.72 ms for /home/nadeko/NadekoBot/NadekoBot.Core/NadekoBot.Core.csproj.
  Restore completed in 6.83 ms for /home/nadeko/NadekoBot/NadekoBot.Tests/NadekoBot.Tests.csproj.
  Restore completed in 39.45 ms for /home/nadeko/NadekoBot/src/NadekoBot/NadekoBot.csproj.
  NadekoBot.Core -> /home/nadeko/NadekoBot/NadekoBot.Core/bin/Release/netcoreapp2.1/NadekoBot.Core.dll
  NadekoBot -> /home/nadeko/NadekoBot/src/NadekoBot/bin/Release/netcoreapp2.1/NadekoBot.dll
  NadekoBot.Tests -> /home/nadeko/NadekoBot/NadekoBot.Tests/bin/Release/netcoreapp2.1/NadekoBot.Tests.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.93
Running NadekoBot. Please wait.
Using launch settings from /home/nadeko/NadekoBot/src/NadekoBot/Properties/launchSettings.json...
-1 01:32:15 ShardsCoordinator | Starting NadekoBot v2.28.3

Unhandled Exception: System.AggregateException: One or more errors occurred. (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)
   at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)
   at StackExchange.Redis.SocketManager.BeginConnect(EndPoint endpoint, ISocketCallback callback, ConnectionMultiplexer multiplexer, TextWriter log) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\SocketManager.cs:line 218
   at StackExchange.Redis.PhysicalConnection.BeginConnect(TextWriter log) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\PhysicalConnection.cs:line 121
   at StackExchange.Redis.PhysicalBridge.GetConnection(TextWriter log) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\PhysicalBridge.cs:line 705
   at StackExchange.Redis.PhysicalBridge.ResetNonConnected() in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\PhysicalBridge.cs:line 301
   at StackExchange.Redis.ServerEndPoint.ResetNonConnected() in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ServerEndPoint.cs:line 55
   at StackExchange.Redis.ConnectionMultiplexer.ResetAllNonConnected() in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 1580
   at StackExchange.Redis.ConnectionMultiplexer.ReconfigureAsync(Boolean first, Boolean reconfigureAll, TextWriter log, EndPoint blame, String cause, Boolean publishReconfigure, CommandFlags publishReconfigureFlags) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 1518
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Func`1 multiplexerFactory, TextWriter log) in C:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 860
   at NadekoBot.Core.Services.ShardsCoordinator..ctor() in /home/nadeko/NadekoBot/NadekoBot.Core/Services/ShardsCoordinator.cs:line 82
   at NadekoBot.Program.Main(String[] args) in /home/nadeko/NadekoBot/src/NadekoBot/Program.cs:line 20
   at NadekoBot.Program.<Main>(String[] args)
Done

**Comment by tanelq** [comment]
Running on ubuntu 18.04.

**Comment by tanelq** [comment]
Thanks! Installing redis fixed the problem.
