### ISSUE TITLE
Unable to DM specific user

### ISSUE THREAD

**Issue by Dandacion** [Kwoth/NadekoBot#2621]
Self hosting on CentOS 7.5

I'm running two seperate instances of the bot from two different directories.
One of my users is unable to receive direct messages from one of the bots. The other is still able to message her without issue and prior to this morning the bot in question was able to too.

Now when attempting to send a message to them either directly through .send or through them using .remind I receive the following error and exception.

`0 14:37:19 CommandHandler | Discord.Net.HttpException: The server responded with error 50007: Cannot send messages to this user
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, String bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.CreateMessageAsync(UInt64 channelId, CreateMessageParams args, RequestOptions options)
   at Discord.Rest.ChannelHelper.SendMessageAsync(IMessageChannel channel, BaseDiscordClient client, String text, Boolean isTTS, Embed embed, RequestOptions options)
   at Discord.Rest.RestDMChannel.Discord.IMessageChannel.SendMessageAsync(String text, Boolean isTTS, Embed embed, RequestOptions options)
   at NadekoBot.Modules.Administration.Administration.SelfCommands.Send(String where, String msg) in /home/Cafe/NadekoBot/NadekoBot.Core/Modules/Administration/SelfCommands.cs:line 470
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   at Discord.Commands.CommandInfo.ExecuteAsync(ICommandContext context, IEnumerable`1 argList, IEnumerable`1 paramList, IServiceProvider services)
0 14:37:19 CommandHandler | Command Executed after 0.000/0.249s
	User: Danda#1950 [109366290774241280]
	Server: Silver Lining ☁ [500620274270601216]
	Channel: bot-commands [501306720778321920]
	Message: .send 500620274270601216|u:385376021467234304 Testing`

**Comment by Kaoticz** [comment]
That's weird, because the other bot in the same server is able to send messages to that user.
Have you tried to restart the glitched one by typing `.die` on Discord?

**Comment by Kwoth** [comment]
So it's a discord error specific error, not 403. no idea why it could happen. Make sure you don't have any filters enabled, and let non-friends dm you.
