### ISSUE TITLE
Nadeko bot suddenly acting odd.

### ISSUE THREAD

**Issue by 1Girl3Balls** [Kwoth/NadekoBot#620]
A few days ago my bot was working perfectly fine. Now, whenever it starts, it produces the following error.

`No google api key found. You will not be able to use music and links won't be shortened.
No trello appkey found. You will not be able to use trello commands.
Forwarding private messages to owner.
No soundcloud Client ID found. Soundcloud streaming is disabled.
No osu! api key found. Song & top score lookups will not work. User lookups still available.
Token is wrong. Don't set a token if you don't have an official BOT account.
Discord.Net.HttpException: The server responded with error 401 (Unauthorized)
   at Discord.Net.Rest.RestSharpEngine.<Send>d__10.MoveNext() in C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net\Net\Rest\SharpRestEngine.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Rest.RestClient.<Send>d__25.MoveNext() in C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net\Net\Rest\RestClient.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Rest.RestClient.<Send>d__211.MoveNext() in C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net\Net\Rest\RestClient.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Discord.DiscordClient.<Login>d__79.MoveNext() in C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net\DiscordClient.cs:line 257
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Discord.DiscordClient.<BeginConnect>d__78.MoveNext() in C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net\DiscordClient.cs:line 202
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.DiscordClient.<BeginConnect>d__78.MoveNext() in C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net\DiscordClient.cs:line 222
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.DiscordClient.<Connect>d__77.MoveNext() in C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net\DiscordClient.cs:line 176
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<>c.<<Main>b__32_3>d.MoveNext() in C:\Users\Kwoth\Source\Repos\NadekoBot\NadekoBot\NadekoBot.cs:line 190
`
The first few lines are normal; I don't have music set up. It's odd because the token is correct. I have checked it, and nothing seems off. But the bot is saying that the token is wrong. I generated a new token, and copied that to credentials.json, but it still produces the same error. Any way I can fix this? Should I just go for a full reinstall of Nadeko bot, and if so, how do I preserve my settings (reminders/greeting messages/leaving messages/etc)?

**Comment by Soundofdarkness** [comment]
Update your Nadeko to the latest version . Discord changed stuff in the API

**Comment by fearnlj01** [comment]
To quote the current update command in use
" You should update the bot to the latest version (0.99.9z) manually https://github.com/Kwoth/NadekoBot/releases if you are getting 400 or 401 error
To update, extract everything from the latest .zip except the /data/ folder into your current NadekoBot folder and you should be gucci

Do not use the updater, it's broken!"

**Comment by 1Girl3Balls** [comment]
Alright, everything works now! Thanks :D
