### ISSUE TITLE
Error when launching NadekoBot exe

### ISSUE THREAD

**Issue by MinksterxD** [Kwoth/NadekoBot#643]
hello when i launch the bot i get this error saying: 

Google API key provided.
No trello appkey found. You will not be able to use trello commands.
Forwarding private messages to owner.
SoundCloud streaming enabled.
No osu! api key found. Song & top score lookups will not work. User lookups still available.
Token is wrong. Don't set a token if you don't have an official BOT account.
Discord.Net.HttpException: The server responded with error 401 (Unauthorized)
   at Discord.Net.Rest.RestSharpEngine.<Send>d__10.MoveNext() in C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net\Net\Rest\SharpRestEngine.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Rest.RestClient.<Send>d__25.MoveNext() in C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net\Net\Rest\RestClient.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Rest.RestClient.<Send>d__21`1.MoveNext() in C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net\Net\Rest\RestClient.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Discord.DiscordClient.<Login>d__79.MoveNext() in C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net\DiscordClient.cs:line 257
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Discord.DiscordClient.<BeginConnect>d__78.MoveNext() in C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net\DiscordClient.cs:line 202
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.DiscordClient.<BeginConnect>d__78.MoveNext() in C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net\DiscordClient.cs:line 222
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.DiscordClient.<Connect>d__77.MoveNext() in C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net\DiscordClient.cs:line 176
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<>c.<<Main>b__32_3>d.MoveNext() in C:\Users\Kwoth\Source\Repos\NadekoBot\NadekoBot\NadekoBot.cs:line 190

please help me

**Comment by Nitix** [comment]
Download the latest version : https://github.com/Kwoth/NadekoBot/releases/tag/v0.99.9z

**Comment by MinksterxD** [comment]
Thank you very much 💃
