### ISSUE TITLE
Can't Run Nadeko

### ISSUE THREAD

**Issue by SleepyRavi** [Kwoth/NadekoBot#803]
So I set up NadekoBot on my Windows PC today. I followed the guide perfectly but somehow when I try to run NadekoBot, a few seconds after the command prompt pops up, i get the error "dotnet has stopped working."

This is what is written on the CMD.

Project Discord.Net (.NETStandard,Version=v1.3) was previously compiled. Skippin
g compilation.
Project Discord.Net.Commands (.NETStandard,Version=v1.3) was previously compiled
. Skipping compilation.
Project NadekoBot (.NETCoreApp,Version=v1.0) was previously compiled. Skipping c
ompilation.
01:17:32 NadekoBot | Starting NadekoBot v1.0-rc2
01:17:33 ShardedDiscordClient | Shard #0 initialized.
01:17:34 ShardedDiscordClient | Shard #0 logged in.

Unhandled Exception: System.PlatformNotSupportedException: The WebSocket protoco
l is not supported on this platform.
   at System.Net.WebSockets.WebSocketHandle.CheckPlatformSupport()
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at Discord.Net.WebSockets.DefaultWebSocketClient.<ConnectInternalAsync>d__24.
MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.Net.WebSockets.DefaultWebSocketClient.<ConnectAsync>d__23.MoveNext
()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.API.DiscordSocketApiClient.<ConnectInternalAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Discord.API.DiscordSocketApiClient.<ConnectInternalAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.API.DiscordSocketApiClient.<ConnectAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.WebSocket.DiscordSocketClient.<ConnectInternalAsync>d__70.MoveNext
()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.WebSocket.DiscordSocketClient.<ConnectInternalAsync>d__70.MoveNext
()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.WebSocket.DiscordSocketClient.<ConnectAsync>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NadekoBot.ShardedDiscordClient.<<ConnectAsync>b__71_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NadekoBot.NadekoBot.<RunAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at NadekoBot.Program.Main(String[] args)
NadekoBot has been succesfully stopped, press any key to close this window. #

**Comment by Kwoth** [comment]
you can't run it on windows7 or older, that's one of the first lines in the guide. :\

**Comment by SleepyRavi** [comment]
I didn't noticed that. Thanks for the reply :+1:
