### ISSUE TITLE
Music thread almost crashed > Timeout

### ISSUE THREAD

**Issue by db9795** [Kwoth/NadekoBot#873]
Always getting this Error Message when I'm trying to stream something from YouTube.

`Music thread almost crashed.                                                                                       System.TimeoutException: The operation has timed out.
at Discord.WebSocket.SocketGuild.<ConnectAudioAsync>d__65.MoveNext() in D:\Musik\Nadeko\NadekoBot\discord.net\src\Discord.Net\WebSocket\Entities\Guilds\SocketGuild.cs:line 289
--- End of stack trace from previous location where exception was thrown---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Discord.WebSocket.SocketGuild.<ConnectAudioAsync>d__65.MoveNext() in D:\Musik\Nadeko\NadekoBot\discord.net\src\Discord.Net\WebSocket\Entities\Guilds\SocketGuild.cs:line 292
--- End of stack trace from previous location where exception was thrown ---                                               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Discord.WebSocket.SocketVoiceChannel.<ConnectAsync>d__12.MoveNext() in D:\Musik\Nadeko\NadekoBot\discord.net\src\Discord.Net\WebSocket\Entities\Channels\SocketVoiceChannel.cs:line 45
--- End of stack trace from previous location where exception was thrown ---                                               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NadekoBot.Modules.Music.Classes.MusicPlayer.<<-ctor>b__61_1>d.MoveNext() in D:\Musik\Nadeko\NadekoBot\src\NadekoBot\Modules\Music\Classes\MusicControls.cs:line 104`

As queuing up still works after, just there's nothing being streamed.
Sometimes the bot ends up not reacting to any commands of the Music module.

**Comment by Helltoad** [comment]
I have the exact same issue but it only happens when i use the !!s and !!d commands to stop the bot from playing music. Tested on 3 separate computers and the issue happens on all of them.

**Comment by db9795** [comment]
Bot stopped making trouble out of nowhere, didn't change anything. All working fine right now.
Will keep it up to date and test all the commands several times.

**Comment by samdivaio** [comment]
Only using `!!d ` command will break the music and its related to Discord not Nadeko.
If that happens you can use `.die ` command to restart if you are running bot with auto-restart.

**Comment by Kwoth** [comment]
Yep, do not use `!!d`

**Comment by db9795** [comment]
Never used !!d

**Comment by Kwoth** [comment]
Your bot probably doesn't have the connect permission then, so it's timing out on connecting. I tested a lot of bugs people reported yesterday, i could reproduce only a few, this one happens to me only when i use !!d, or when bot is disconnected for some reason.

**Comment by Protectator** [comment]
Just encountered this bug over night. It has been streaming YouTube videos fine for two or three days, and this is the first time I get this error. I checked the server, and no one seem to have used `!!d`, only one `!!stop`.

```
09:02:36 MusicControls | System.TimeoutException: The operation has timed out.
   at Discord.WebSocket.SocketGuild.<ConnectAudioAsync>d__151.MoveNext() in /home/protectator/nadeko/NadekoBot/Discord.Net/src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs:line 477
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.WebSocket.SocketGuild.<ConnectAudioAsync>d__151.MoveNext() in /home/protectator/nadeko/NadekoBot/Discord.Net/src/Discord.Net.WebSocket/Entities/Guilds/SocketGuild.cs:line 480
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.SocketVoiceChannel.<ConnectAsync>d__14.MoveNext() in /home/protectator/nadeko/NadekoBot/Discord.Net/src/Discord.Net.WebSocket/Entities/Channels/SocketVoiceChannel.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Music.Classes.MusicPlayer.<<-ctor>b__86_1>d.MoveNext() in /home/protectator/nadeko/NadekoBot/src/NadekoBot/Modules/Music/Classes/MusicControls.cs:line 146
```

**Comment by shikhir-arora** [comment]
@Protectator - https://github.com/Kwoth/NadekoBot/issues/1053#issuecomment-291206391
