### ISSUE TITLE
Can't start the bot

### ISSUE THREAD

**Issue by justinkruit** [Kwoth/NadekoBot#878]
Every time I try to start it with "bash nadeko_run.sh", I get this crash (catched with tmux). I have no idea how to fix it, and I'm 100% sure it's the correct token. The bot is installed with nadeko_installer.sh.

```
[1;23r[H
NadekoBot 1.0[1;24r[H[2;14H
[1;23r[H[2BMirai was here.[1;24r[H[3;16H
[1;23r[H[3BDotnet installed.[1;24r[H[4;18H
[1;23r[H[4BRunning NadekoBot. Please wait.[1;24r[H[5;32H
[1;23r[H[5BProject Discord.Net (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.[?25l[24;1H[30m[42m[discordbo0:dash*                               "whereisassange" 08:09 11-Dec-16(B[m[24;1H[1;24r[H[7;15H[?12l[?25h
[1;23r[H[7BProject Discord.Net.Commands (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.[1;24r[H[9;24H
[1;23r[H[9BProject NadekoBot (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.[1;24r[H[11;12H
[1;23r[H[11B[37m08:09:51 NadekoBot | Starting NadekoBot v1.0-rc2[1;24r[H[12;49H(B[m
[1;23r[H[13d[37m08:09:51 ShardedDiscordClient | Shard #0 initialized.[1;24r[H[13;54H(B[m

[1;23r[H[15dUnhandled Exception:[1;24r[H[15;21H[1;23r[H[15;21H [1;24r[H[15;22H[1;23r[H[15;22HSystem.ArgumentException: Token validation failed[1;24r[H[15;71H
[1;23r[H[16dParameter name: token ---> Discord.Net.HttpException: The server responded with error 401 (Unauthorized): "401: Unauthorized"[1;24r[H[17;46H
[1;23r[H[18d   at Discord.Net.Rest.DefaultRestClient.<SendInternalAsync>d__16.MoveNext() in /root/NadekoBot/discord.net/src/Discord.Net/Net/Rest/DefaultRestClient.cs:line 157[1;24r[H[20;3H
[1;23r[H[21d--- End of stack trace from previous location where exception was thrown ---[1;24r[H[21;77H
[1;23r[H[22d   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()[1;24r[H[22;69H
[1;23r[H[23d   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)[1;24r[H[23;21H[1;23r[H[23d
[1;24r[H[23d[1;23r[H[23d   at Discord.Net.Rest.DefaultRestClient.<SendAsync>d__13.MoveNext() in /root/NadekoBot/discord.net/src/Discord.Net/Net/Rest/DefaultRestClient.cs:line 74[1;24r[H[23;74H[1;23r[H[23d
[1;24r[H[23d[1;23r[H[23d--- End of stack trace from previous location where exception was thrown ---[1;24r[H[23;77H[1;23r[H[23d
[1;24r[H[23d[1;23r[H[23d   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()[1;24r[H[23;69H[1;23r[H[23d
[1;24r[H[23d[1;23r[H[23d   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)[1;24r[H[23;21H[1;23r[H[23d
[1;24r[H[23d[1;23r[H[23d   at Discord.Net.Queue.RestRequest.<SendAsync>d__33.MoveNext() in /root/NadekoBot/discord.net/src/Discord.Net/Net/Queue/RestRequest.cs:line 58[1;24r[H[23;64H[1;23r[H[23d
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Queue.RequestQueueBucket.<SendAsyncInternal>d__16.MoveNext() in /root/NadekoBot/discord.net/src/Discord.Net/Net/Queue/RequestQueueBucket.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Queue.RequestQueueBucket.<SendAsync>d__15.MoveNext() in /root/NadekoBot/discord.net/src/Discord.Net/Net/Queue/RequestQueueBucket.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaite[1;24r[H[23;49H[1;23r[H[23;49Hr.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Queue.RequestQueue.<SendAsync>d__19.MoveNext() in /root/NadekoBot/discord.net/src/Discord.Net/Net/Queue/RequestQueue.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendInternalAsync>d__46.MoveNext() in /root/NadekoBot/discord.net/src/Discord.Net/API/DiscordRestApiClient.cs:line 206
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendAsync>d__36`1.MoveNext() in /root/NadekoBot/discord.net/src/Discord.Net/API/DiscordRestApiClient.cs:line 162
--- End [1;24r[H[23;9H[1;23r[H[23;9Hof stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<GetMyUserAsync>d__119.MoveNext() in /root/NadekoBot/discord.net/src/Discord.Net/API/DiscordRestApiClient.cs:line 993
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.DiscordRestClient.<ValidateTokenAsync>d__36.MoveNext() in /root/NadekoBot/discord.net/src/Discord.Net/Rest/DiscordRestClient.cs:line 112
   --- End of inner exception stack trace ---
   at Discord.Rest.DiscordRestClient.<ValidateTokenAsync>d__36.MoveNext() in /root/NadekoBot/discord.net/src/Discord.Net/Rest/DiscordRestClient.cs:line 121
--- End of st[1;24r[H[23;14H[1;23r[H[23;14Hack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.DiscordRestClient.<LoginInternalAsync>d__35.MoveNext() in /root/NadekoBot/discord.net/src/Discord.Net/Rest/DiscordRestClient.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Rest.DiscordRestClient.<LoginInternalAsync>d__35.MoveNext() in /root/NadekoBot/discord.net/src/Discord.Net/Rest/DiscordRestClient.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.DiscordRestClient.<LoginAsync>d__34.MoveNext() in /root/N[1;24r[H[23;77H[1;23r[H[23;77HadekoBot/discord.net/src/Discord.Net/Rest/DiscordRestClient.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.ShardedDiscordClient.<>c__DisplayClass70_0.<<LoginAsync>b__0>d.MoveNext() in /root/NadekoBot/src/NadekoBot/ShardedDiscordClient.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAsync>d__47.MoveNext() in /root/NadekoBot/src/NadekoBot/NadekoBot.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.Ta[1;24r[H[23;41H[1;23r[H[23;41HskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__48.MoveNext() in /root/NadekoBot/src/NadekoBot/NadekoBot.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Program.Main(String[] args) in /root/NadekoBot/src/NadekoBot/Program.cs:line 6
[1;24r[H[23d[1;23r[H[23dDone[1;24r[H[23;5H[1;23r[H[23d
```

**Comment by samdivaio** [comment]
Check your `credentials.json ` and add your bot token.

**Comment by Kwoth** [comment]
try regenerating a token and adding that new one.

**Comment by justinkruit** [comment]
@Kwoth @samdivaio I've added a bot token, and I've also already regenerated a code, added that one, and tried again, but it just isn't working. I've also tried 0.9.99 (the last one), and that one also couldn't connect with the token. I've tried multiple bots also, and still didn't work.

**Comment by samdivaio** [comment]
Then I am guessing you changed some format in json file, can you screenshot it, you can blur out half of the tokens and api etc that you have.

**Comment by justinkruit** [comment]
@samdivaio here it is 
![point blur_dec112016_002125](https://cloud.githubusercontent.com/assets/1642830/21076884/eae8dc52-bf37-11e6-8efa-4e8a451bf73a.jpg)

**Comment by samdivaio** [comment]
Your token looks really small 🤔

**Comment by justinkruit** [comment]
It's a complete 32 symbols long token beneath the blur tho

**Comment by samdivaio** [comment]
That's client's secret then, the token should be below it in discord devs

**Comment by samdivaio** [comment]
Should be here ![token](https://cdn.discordapp.com/attachments/249455731584008192/257288355941842944/image.jpg)

**Comment by justinkruit** [comment]
Is there a corner available? I need one to cry in...

**Comment by samdivaio** [comment]
It's okay 😄
@Nadeko pat @justinkruit
