### ISSUE TITLE
Nadeko fails to start on stable AND latest builds

### ISSUE THREAD

**Issue by Kilovice** [Kwoth/NadekoBot#910]
I've just setup Nadeko bot and have been unable to get it to start. Compilation succeeds and Shard #0 gets initialized, however this error occurs:
`Unhandled Exception: System.ArgumentException: Token validation failed
Parameter name: token ---> Discord.Net.HttpException: The server responded with error 401 (Unauthorized): "401: Unauthorized"
   at Discord.Net.Rest.DefaultRestClient.<SendInternalAsync>d__16.MoveNext() in C:\Users\Zack\Documents\Nadeko\NadekoBot\discord.net\src\Discord.Net\Net\Rest\DefaultRestClient.cs:line 157
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Rest.DefaultRestClient.<SendAsync>d__13.MoveNext() in C:\Users\Zack\Documents\Nadeko\NadekoBot\discord.net\src\Discord.Net\Net\Rest\DefaultRestClient.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Queue.RestRequest.<SendAsync>d__33.MoveNext() in C:\Users\Zack\Documents\Nadeko\NadekoBot\discord.net\src\Discord.Net\Net\Queue\RestRequest.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Queue.RequestQueueBucket.<SendAsyncInternal>d__16.MoveNext() in C:\Users\Zack\Documents\Nadeko\NadekoBot\discord.net\src\Discord.Net\Net\Queue\RequestQueueBucket.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Queue.RequestQueueBucket.<SendAsync>d__15.MoveNext() in C:\Users\Zack\Documents\Nadeko\NadekoBot\discord.net\src\Discord.Net\Net\Queue\RequestQueueBucket.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Queue.RequestQueue.<SendAsync>d__19.MoveNext() in C:\Users\Zack\Documents\Nadeko\NadekoBot\discord.net\src\Discord.Net\Net\Queue\RequestQueue.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendInternalAsync>d__46.MoveNext() in C:\Users\Zack\Documents\Nadeko\NadekoBot\discord.net\src\Discord.Net\API\DiscordRestApiClient.cs:line 206
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendAsync>d__36`1.MoveNext() in C:\Users\Zack\Documents\Nadeko\NadekoBot\discord.net\src\Discord.Net\API\DiscordRestApiClient.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<GetMyUserAsync>d__119.MoveNext() in C:\Users\Zack\Documents\Nadeko\NadekoBot\discord.net\src\Discord.Net\API\DiscordRestApiClient.cs:line 993
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.DiscordRestClient.<ValidateTokenAsync>d__36.MoveNext() in C:\Users\Zack\Documents\Nadeko\NadekoBot\discord.net\src\Discord.Net\Rest\DiscordRestClient.cs:line 112
   --- End of inner exception stack trace ---
   at Discord.Rest.DiscordRestClient.<ValidateTokenAsync>d__36.MoveNext() in C:\Users\Zack\Documents\Nadeko\NadekoBot\discord.net\src\Discord.Net\Rest\DiscordRestClient.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.DiscordRestClient.<LoginInternalAsync>d__35.MoveNext() in C:\Users\Zack\Documents\Nadeko\NadekoBot\discord.net\src\Discord.Net\Rest\DiscordRestClient.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Rest.DiscordRestClient.<LoginInternalAsync>d__35.MoveNext() in C:\Users\Zack\Documents\Nadeko\NadekoBot\discord.net\src\Discord.Net\Rest\DiscordRestClient.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.DiscordRestClient.<LoginAsync>d__34.MoveNext() in C:\Users\Zack\Documents\Nadeko\NadekoBot\discord.net\src\Discord.Net\Rest\DiscordRestClient.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.ShardedDiscordClient.<>c__DisplayClass70_0.<<LoginAsync>b__0>d.MoveNext() in C:\Users\Zack\Documents\Nadeko\NadekoBot\src\NadekoBot\ShardedDiscordClient.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAsync>d__47.MoveNext() in C:\Users\Zack\Documents\Nadeko\NadekoBot\src\NadekoBot\NadekoBot.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.NadekoBot.<RunAndBlockAsync>d__48.MoveNext() in C:\Users\Zack\Documents\Nadeko\NadekoBot\src\NadekoBot\NadekoBot.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Program.Main(String[] args) in C:\Users\Zack\Documents\Nadeko\NadekoBot\src\NadekoBot\Program.cs:line 6
NadekoBot has been succesfully stopped, press any key to close this window.`

On a side note, my credentials.json file is as follows (with Secret and Owner IDs hidden):
'{
  "ClientId": 260646035271974913,
  "BotId": 260646035271974913,
  "Token": "**Insert Secret Here :)**",
  "OwnerIds": [
    NothingToSeeHere,StillNothingToSee
  ],
  "LoLApiKey": "",
  "GoogleApiKey": "",
  "MashapeKey": "",
  "OsuApiKey": "",
  "SoundCloudClientId": "",
  "Db": {
    "Type": "sqlite",
    "ConnectionString": "Filename=./data/NadekoBot.db"
  },
  "TotalShards": 1
}'

**Comment by samdivaio** [comment]
Not secret, insert you Bot App **Token**
