### ISSUE TITLE
Music Thread Crashed. - Issue

### ISSUE THREAD

**Issue by Jacob17256** [Kwoth/NadekoBot#918]
Hey, not sure if this is on my end or an error with the bot. When queuing music, sometimes the bot leaves and rejoins the channel, sometimes the bot stops playing music and sometimes the commands don't work. In the latest crash, the bot gave me this message:

```
Music thread crashed.
System.ArgumentException: This channel is not part of the current server.
Parameter name: channel
   at Discord.Audio.AudioClient.<Join>d__50.MoveNext() in C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net.Audio\AudioClient.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Audio.AudioService.<Join>d__29.MoveNext() in C:\Users\Kwoth\Source\Repos\NadekoBot\discord.net\src\Discord.Net.Audio\AudioService.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NadekoBot.Modules.Music.Classes.MusicPlayer.<<-ctor>b__61_1>d.MoveNext() in C:\Users\Kwoth\Source\Repos\NadekoBot\NadekoBot\Modules\Music\Classes\MusicControls.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NadekoBot.Modules.Music.Classes.MusicPlayer.<<-ctor>b__61_1>d.MoveNext() in C:\Users\Kwoth\Source\Repos\NadekoBot\NadekoBot\Modules\Music\Classes\MusicControls.cs:line 138
Failed resolving the link.Response status code does not indicate success: 403 (Forbidden).
```

When the bot leaves and rejoins, I receive this message:
```

Severity: WarningExceptionMessage: -Message: Unknown Opcode: 8
Severity: ErrorExceptionMessage: Connection lostMessage: Disconnected
Severity: WarningExceptionMessage: -Message: Unknown Opcode: 8
```

Thanks! 

Jacob

**Comment by samdivaio** [comment]
Upgrade your bot to [Nadeko 1,0](http://nadekobot.readthedocs.io/en/latest/)
