### ISSUE TITLE
CommandHandler Issue

### ISSUE THREAD

**Issue by Vanillaah** [Kwoth/NadekoBot#951]
I get the error message:
CommandHandler | No owner channels created! Make sure you've specified correct OwnerId in the credentials.json file.
When running NadekoBot and I do not know what I have specified wrongly~ 
Blurred out my personal credits only in the screenshot because I suppose this is public.
For ClientId and BotId, I used the APP DETAILS > Client ID: on discordapp.com/developers/applications/me.
For the token I used APP BOT USER > Token: on the same site as above.
For OwnerIds I did \@MyDiscordName#MyHashtag and copy pasted only the numbers.
I hope anyone has anyclue whats the issue.

![credentials json blurred](https://cloud.githubusercontent.com/assets/24986403/21748710/918f9b9a-d58b-11e6-9e8f-0a22a54c40b7.png)
![what do i even do wrong](https://cloud.githubusercontent.com/assets/24986403/21748711/91958cc6-d58b-11e6-9d44-62cb3f7460b1.png)

**Comment by Kwoth** [comment]
no you need to type `\@YourDiscordName` and then copy only the numbers you get (its a long number)

**Comment by Vanillaah** [comment]
I have done that :/

**Comment by Vanillaah** [comment]
![does not work](https://cloud.githubusercontent.com/assets/24986403/21748968/788de086-d593-11e6-8eda-79b716fb6fc7.png)

**Comment by Vanillaah** [comment]
I do not see my mistake in here o:

**Comment by Kwoth** [comment]
try removing the trailing comma

**Comment by Vanillaah** [comment]
dotnet crashes when i do that

**Comment by Vanillaah** [comment]
11:14:38 BotCredentials | Could not parse the JSON file. Error on line number '8': ']
"LoLApiKey": "",'.
11:14:38 BotCredentials | System.FormatException: Could not parse the JSON file. Error on line number '8': ']
"LoLApiKey": "",'. ---> Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: ". Path 'OwnerIds', line 8, position 2.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at NadekoBot.Services.Impl.BotCredentials..ctor() in C:\Users\Thorsten\Desktop\Nadeko\NadekoBot\src\NadekoBot\Services\Impl\BotCredentials.cs:line 45

**Comment by Kwoth** [comment]
try `"OwnerIds": [youridhere],`

**Comment by Vanillaah** [comment]
still the same error

**Comment by samdivaio** [comment]
Its a json file, not a regular text file you have removed the spaces before you owener id, use the credentials example.json and copy paste everything.
Remember do not add any extra character or white space.

**Comment by Vanillaah** [comment]
even with copy pasting the one kwoth send me it does not work

**Comment by Vanillaah** [comment]
i have checked if its just my discord, but others accounts dont work either

**Comment by Vanillaah** [comment]
i re-added nadeko to my server and it worked o:

**Comment by Vanillaah** [comment]
now i just need to get this thing with google to work xD
